#ifndef MOVE_IDS_H
#define MOVE_IDS_H

#define move_target_selected 0
#define move_target_depends 1
#define move_target_random 4
#define move_target_both 8
#define move_target_user 0x10
#define move_target_foes_and_ally 0x20
#define move_target_opponent_field 0x40

#define MOVE_CONFUSION_DMG ((sizeof(move_table) / sizeof(struct move_info)))

#define    MOVE_POUND    1    //拍击
#define    MOVE_KARATE_CHOP    2    //空手劈
#define    MOVE_DOUBLE_SLAP    3    //连环巴掌
#define    MOVE_COMET_PUNCH    4    //连续拳
#define    MOVE_MEGA_PUNCH    5    //百万吨重拳
#define    MOVE_PAY_DAY    6    //聚宝功
#define    MOVE_FIRE_PUNCH    7    //火焰拳
#define    MOVE_ICE_PUNCH    8    //冰冻拳
#define    MOVE_THUNDER_PUNCH    9    //雷电拳
#define    MOVE_SCRATCH    10    //抓
#define    MOVE_VICE_GRIP    11    //夹住
#define    MOVE_GUILLOTINE    12    //断头钳
#define    MOVE_RAZOR_WIND    13    //旋风刀
#define    MOVE_SWORDS_DANCE    14    //剑舞
#define    MOVE_CUT    15    //居合斩
#define    MOVE_GUST    16    //起风
#define    MOVE_WING_ATTACK    17    //翅膀攻击
#define    MOVE_WHIRLWIND    18    //吹飞
#define    MOVE_FLY    19    //飞翔
#define    MOVE_BIND    20    //绑紧
#define    MOVE_SLAM    21    //摔打
#define    MOVE_VINE_WHIP    22    //藤鞭
#define    MOVE_STOMP    23    //踩踏
#define    MOVE_DOUBLE_KICK    24    //二连踢
#define    MOVE_MEGA_KICK    25    //百万吨重踢
#define    MOVE_JUMP_KICK    26    //飞踢
#define    MOVE_ROLLING_KICK    27    //回旋踢
#define    MOVE_SAND_ATTACK    28    //泼沙
#define    MOVE_HEADBUTT    29    //头锤
#define    MOVE_HORN_ATTACK    30    //角撞
#define    MOVE_FURY_ATTACK    31    //乱击
#define    MOVE_HORN_DRILL    32    //角钻
#define    MOVE_TACKLE    33    //撞击
#define    MOVE_BODY_SLAM    34    //泰山压顶
#define    MOVE_WRAP    35    //紧束
#define    MOVE_TAKE_DOWN    36    //猛撞
#define    MOVE_THRASH    37    //大闹一番
#define    MOVE_DOUBLEEDGE    38    //舍身冲撞
#define    MOVE_TAIL_WHIP    39    //摇尾巴
#define    MOVE_POISON_STING    40    //毒针
#define    MOVE_TWINEEDLE    41    //双针
#define    MOVE_PIN_MISSILE    42    //飞弹针
#define    MOVE_LEER    43    //瞪眼
#define    MOVE_BITE    44    //咬住
#define    MOVE_GROWL    45    //叫声
#define    MOVE_ROAR    46    //吼叫
#define    MOVE_SING    47    //唱歌
#define    MOVE_SUPERSONIC    48    //超音波
#define    MOVE_SONIC_BOOM    49    //音爆
#define    MOVE_DISABLE    50    //定身法
#define    MOVE_ACID    51    //溶解液
#define    MOVE_EMBER    52    //火花
#define    MOVE_FLAMETHROWER    53    //喷射火焰
#define    MOVE_MIST    54    //白雾
#define    MOVE_WATER_GUN    55    //水枪
#define    MOVE_HYDRO_PUMP    56    //水炮
#define    MOVE_SURF    57    //冲浪
#define    MOVE_ICE_BEAM    58    //冰冻光束
#define    MOVE_BLIZZARD    59    //暴风雪
#define    MOVE_PSYBEAM    60    //幻象光线
#define    MOVE_BUBBLE_BEAM    61    //泡沫光线
#define    MOVE_AURORA_BEAM    62    //极光束
#define    MOVE_HYPER_BEAM    63    //破坏光线
#define    MOVE_PECK    64    //啄
#define    MOVE_DRILL_PECK    65    //啄钻
#define    MOVE_SUBMISSION    66    //地狱翻滚
#define    MOVE_LOW_KICK    67    //踢倒
#define    MOVE_COUNTER    68    //双倍奉还
#define    MOVE_SEISMIC_TOSS    69    //地球上投
#define    MOVE_STRENGTH    70    //怪力
#define    MOVE_ABSORB    71    //吸取
#define    MOVE_MEGA_DRAIN    72    //超级吸取
#define    MOVE_LEECH_SEED    73    //寄生种子
#define    MOVE_GROWTH    74    //生长
#define    MOVE_RAZOR_LEAF    75    //飞叶快刀
#define    MOVE_SOLAR_BEAM    76    //日光束
#define    MOVE_POISON_POWDER    77    //毒粉
#define    MOVE_STUN_SPORE    78    //麻痹粉
#define    MOVE_SLEEP_POWDER    79    //催眠粉
#define    MOVE_PETAL_DANCE    80    //花瓣舞
#define    MOVE_STRING_SHOT    81    //吐丝
#define    MOVE_DRAGON_RAGE    82    //龙之怒
#define    MOVE_FIRE_SPIN    83    //火焰旋涡
#define    MOVE_THUNDER_SHOCK    84    //电击
#define    MOVE_THUNDERBOLT    85    //十万伏特
#define    MOVE_THUNDER_WAVE    86    //电磁波
#define    MOVE_THUNDER    87    //打雷
#define    MOVE_ROCK_THROW    88    //落石
#define    MOVE_EARTHQUAKE    89    //地震
#define    MOVE_FISSURE    90    //地裂
#define    MOVE_DIG    91    //挖洞
#define    MOVE_TOXIC    92    //剧毒
#define    MOVE_CONFUSION    93    //念力
#define    MOVE_PSYCHIC    94    //精神强念
#define    MOVE_HYPNOSIS    95    //催眠术
#define    MOVE_MEDITATE    96    //瑜伽姿势
#define    MOVE_AGILITY    97    //高速移动
#define    MOVE_QUICK_ATTACK    98    //电光一闪
#define    MOVE_RAGE    99    //愤怒
#define    MOVE_TELEPORT    100    //瞬间移动
#define    MOVE_NIGHT_SHADE    101    //黑夜魔影
#define    MOVE_MIMIC    102    //模仿
#define    MOVE_SCREECH    103    //刺耳声
#define    MOVE_DOUBLE_TEAM    104    //影子分身
#define    MOVE_RECOVER    105    //自我再生
#define    MOVE_HARDEN    106    //变硬
#define    MOVE_MINIMIZE    107    //变小
#define    MOVE_SMOKESCREEN    108    //烟幕
#define    MOVE_CONFUSE_RAY    109    //奇异之光
#define    MOVE_WITHDRAW    110    //缩入壳中
#define    MOVE_DEFENSE_CURL    111    //变圆
#define    MOVE_BARRIER    112    //屏障
#define    MOVE_LIGHT_SCREEN    113    //光墙
#define    MOVE_HAZE    114    //黑雾
#define    MOVE_REFLECT    115    //反射壁
#define    MOVE_FOCUS_ENERGY    116    //聚气
#define    MOVE_BIDE    117    //忍耐
#define    MOVE_METRONOME    118    //挥指
#define    MOVE_MIRROR_MOVE    119    //鹦鹉学舌
#define    MOVE_SELFDESTRUCT    120    //自爆
#define    MOVE_EGG_BOMB    121    //炸蛋
#define    MOVE_LICK    122    //舌舔
#define    MOVE_SMOG    123    //浊雾
#define    MOVE_SLUDGE    124    //污泥攻击
#define    MOVE_BONE_CLUB    125    //骨棒
#define    MOVE_FIRE_BLAST    126    //大字爆炎
#define    MOVE_WATERFALL    127    //攀瀑
#define    MOVE_CLAMP    128    //贝壳夹击
#define    MOVE_SWIFT    129    //高速星星
#define    MOVE_SKULL_BASH    130    //火箭头锤
#define    MOVE_SPIKE_CANNON    131    //尖刺加农炮
#define    MOVE_CONSTRICT    132    //缠绕
#define    MOVE_AMNESIA    133    //瞬间失忆
#define    MOVE_KINESIS    134    //折弯汤匙
#define    MOVE_SOFTBOILED    135    //生蛋
#define    MOVE_HIGH_JUMP_KICK    136    //飞膝踢
#define    MOVE_GLARE    137    //大蛇瞪眼
#define    MOVE_DREAM_EATER    138    //食梦
#define    MOVE_POISON_GAS    139    //毒瓦斯
#define    MOVE_BARRAGE    140    //投球
#define    MOVE_LEECH_LIFE    141    //吸血
#define    MOVE_LOVELY_KISS    142    //恶魔之吻
#define    MOVE_SKY_ATTACK    143    //神鸟猛击
#define    MOVE_TRANSFORM    144    //变身
#define    MOVE_BUBBLE    145    //泡沫
#define    MOVE_DIZZY_PUNCH    146    //迷昏拳
#define    MOVE_SPORE    147    //蘑菇孢子
#define    MOVE_FLASH    148    //闪光
#define    MOVE_PSYWAVE    149    //精神波
#define    MOVE_SPLASH    150    //跃起
#define    MOVE_ACID_ARMOR    151    //溶化
#define    MOVE_CRABHAMMER    152    //蟹钳锤
#define    MOVE_EXPLOSION    153    //大爆炸
#define    MOVE_FURY_SWIPES    154    //乱抓
#define    MOVE_BONEMERANG    155    //骨头回力镖
#define    MOVE_REST    156    //睡觉
#define    MOVE_ROCK_SLIDE    157    //岩崩
#define    MOVE_HYPER_FANG    158    //必杀门牙
#define    MOVE_SHARPEN    159    //棱角化
#define    MOVE_CONVERSION    160    //纹理
#define    MOVE_TRI_ATTACK    161    //三重攻击
#define    MOVE_SUPER_FANG    162    //愤怒门牙
#define    MOVE_SLASH    163    //劈开
#define    MOVE_SUBSTITUTE    164    //替身
#define    MOVE_STRUGGLE    165    //挣扎
#define    MOVE_SKETCH    166    //写生
#define    MOVE_TRIPLE_KICK    167    //三连踢
#define    MOVE_THIEF    168    //小偷
#define    MOVE_SPIDER_WEB    169    //蛛网
#define    MOVE_MIND_READER    170    //心之眼
#define    MOVE_NIGHTMARE    171    //恶梦
#define    MOVE_FLAME_WHEEL    172    //火焰轮
#define    MOVE_SNORE    173    //打鼾
#define    MOVE_CURSE    174    //诅咒
#define    MOVE_FLAIL    175    //抓狂
#define    MOVE_CONVERSION_2    176    //纹理２
#define    MOVE_AEROBLAST    177    //气旋攻击
#define    MOVE_COTTON_SPORE    178    //棉孢子
#define    MOVE_REVERSAL    179    //起死回生
#define    MOVE_SPITE    180    //怨恨
#define    MOVE_POWDER_SNOW    181    //细雪
#define    MOVE_PROTECT    182    //守住
#define    MOVE_MACH_PUNCH    183    //音速拳
#define    MOVE_SCARY_FACE    184    //鬼面
#define    MOVE_FEINT_ATTACK    185    //出奇一击
#define    MOVE_SWEET_KISS    186    //天使之吻
#define    MOVE_BELLY_DRUM    187    //腹鼓
#define    MOVE_SLUDGE_BOMB    188    //污泥炸弹
#define    MOVE_MUDSLAP    189    //掷泥
#define    MOVE_OCTAZOOKA    190    //章鱼桶炮
#define    MOVE_SPIKES    191    //撒菱
#define    MOVE_ZAP_CANNON    192    //电磁炮
#define    MOVE_FORESIGHT    193    //识破
#define    MOVE_DESTINY_BOND    194    //同命
#define    MOVE_PERISH_SONG    195    //灭亡之歌
#define    MOVE_ICY_WIND    196    //冰冻之风
#define    MOVE_DETECT    197    //看穿
#define    MOVE_BONE_RUSH    198    //骨棒乱打
#define    MOVE_LOCKON    199    //锁定
#define    MOVE_OUTRAGE    200    //逆鳞
#define    MOVE_SANDSTORM    201    //沙暴
#define    MOVE_GIGA_DRAIN    202    //终极吸取
#define    MOVE_ENDURE    203    //挺住
#define    MOVE_CHARM    204    //撒娇
#define    MOVE_ROLLOUT    205    //滚动
#define    MOVE_FALSE_SWIPE    206    //点到为止
#define    MOVE_SWAGGER    207    //虚张声势
#define    MOVE_MILK_DRINK    208    //喝牛奶
#define    MOVE_SPARK    209    //电光
#define    MOVE_FURY_CUTTER    210    //连斩
#define    MOVE_STEEL_WING    211    //钢翼
#define    MOVE_MEAN_LOOK    212    //黑色目光
#define    MOVE_ATTRACT    213    //迷人
#define    MOVE_SLEEP_TALK    214    //梦话
#define    MOVE_HEAL_BELL    215    //治愈铃声
#define    MOVE_RETURN    216    //报恩
#define    MOVE_PRESENT    217    //礼物
#define    MOVE_FRUSTRATION    218    //迁怒
#define    MOVE_SAFEGUARD    219    //神秘守护
#define    MOVE_PAIN_SPLIT    220    //分担痛楚
#define    MOVE_SACRED_FIRE    221    //神圣之火
#define    MOVE_MAGNITUDE    222    //震级
#define    MOVE_DYNAMIC_PUNCH    223    //爆裂拳
#define    MOVE_MEGAHORN    224    //超级角击
#define    MOVE_DRAGON_BREATH    225    //龙息
#define    MOVE_BATON_PASS    226    //接棒
#define    MOVE_ENCORE    227    //再来一次
#define    MOVE_PURSUIT    228    //追打
#define    MOVE_RAPID_SPIN    229    //高速旋转
#define    MOVE_SWEET_SCENT    230    //甜甜香气
#define    MOVE_IRON_TAIL    231    //铁尾
#define    MOVE_METAL_CLAW    232    //金属爪
#define    MOVE_VITAL_THROW    233    //借力摔
#define    MOVE_MORNING_SUN    234    //晨光
#define    MOVE_SYNTHESIS    235    //光合作用
#define    MOVE_MOONLIGHT    236    //月光
#define    MOVE_HIDDEN_POWER    237    //觉醒力量
#define    MOVE_CROSS_CHOP    238    //十字劈
#define    MOVE_TWISTER    239    //龙卷风
#define    MOVE_RAIN_DANCE    240    //求雨
#define    MOVE_SUNNY_DAY    241    //大晴天
#define    MOVE_CRUNCH    242    //咬碎
#define    MOVE_MIRROR_COAT    243    //镜面反射
#define    MOVE_PSYCH_UP    244    //自我暗示
#define    MOVE_EXTREME_SPEED    245    //神速
#define    MOVE_ANCIENT_POWER    246    //原始之力
#define    MOVE_SHADOW_BALL    247    //暗影球
#define    MOVE_FUTURE_SIGHT    248    //预知未来
#define    MOVE_ROCK_SMASH    249    //碎岩
#define    MOVE_WHIRLPOOL    250    //潮旋
#define    MOVE_BEAT_UP    251    //围攻
#define    MOVE_FAKE_OUT    252    //击掌奇袭
#define    MOVE_UPROAR    253    //吵闹
#define    MOVE_STOCKPILE    254    //蓄力
#define    MOVE_SPIT_UP    255    //喷出
#define    MOVE_SWALLOW    256    //吞下
#define    MOVE_HEAT_WAVE    257    //热风
#define    MOVE_HAIL    258    //冰雹
#define    MOVE_TORMENT    259    //无理取闹
#define    MOVE_FLATTER    260    //吹捧
#define    MOVE_WILLOWISP    261    //鬼火
#define    MOVE_MEMENTO    262    //临别礼物
#define    MOVE_FACADE    263    //硬撑
#define    MOVE_FOCUS_PUNCH    264    //真气拳
#define    MOVE_SMELLING_SALTS    265    //清醒
#define    MOVE_FOLLOW_ME    266    //看我嘛
#define    MOVE_NATURE_POWER    267    //自然之力
#define    MOVE_CHARGE    268    //充电
#define    MOVE_TAUNT    269    //挑衅
#define    MOVE_HELPING_HAND    270    //帮助
#define    MOVE_TRICK    271    //戏法
#define    MOVE_ROLE_PLAY    272    //扮演
#define    MOVE_WISH    273    //祈愿
#define    MOVE_ASSIST    274    //借助
#define    MOVE_INGRAIN    275    //扎根
#define    MOVE_SUPERPOWER    276    //蛮力
#define    MOVE_MAGIC_COAT    277    //魔法反射
#define    MOVE_RECYCLE    278    //回收利用
#define    MOVE_REVENGE    279    //报复
#define    MOVE_BRICK_BREAK    280    //劈瓦
#define    MOVE_YAWN    281    //哈欠
#define    MOVE_KNOCK_OFF    282    //拍落
#define    MOVE_ENDEAVOR    283    //蛮干
#define    MOVE_ERUPTION    284    //喷火
#define    MOVE_SKILL_SWAP    285    //特性互换
#define    MOVE_IMPRISON    286    //封印
#define    MOVE_REFRESH    287    //焕然一新
#define    MOVE_GRUDGE    288    //怨念
#define    MOVE_SNATCH    289    //抢夺
#define    MOVE_SECRET_POWER    290    //秘密之力
#define    MOVE_DIVE    291    //潜水
#define    MOVE_ARM_THRUST    292    //猛推
#define    MOVE_CAMOUFLAGE    293    //保护色
#define    MOVE_TAIL_GLOW    294    //萤火
#define    MOVE_LUSTER_PURGE    295    //洁净光芒
#define    MOVE_MIST_BALL    296    //薄雾球
#define    MOVE_FEATHER_DANCE    297    //羽毛舞
#define    MOVE_TEETER_DANCE    298    //摇晃舞
#define    MOVE_BLAZE_KICK    299    //火焰踢
#define    MOVE_MUD_SPORT    300    //玩泥巴
#define    MOVE_ICE_BALL    301    //冰球
#define    MOVE_NEEDLE_ARM    302    //尖刺臂
#define    MOVE_SLACK_OFF    303    //偷懒
#define    MOVE_HYPER_VOICE    304    //巨声
#define    MOVE_POISON_FANG    305    //剧毒牙
#define    MOVE_CRUSH_CLAW    306    //撕裂爪
#define    MOVE_BLAST_BURN    307    //爆炸烈焰
#define    MOVE_HYDRO_CANNON    308    //加农水炮
#define    MOVE_METEOR_MASH    309    //彗星拳
#define    MOVE_ASTONISH    310    //惊吓
#define    MOVE_WEATHER_BALL    311    //气象球
#define    MOVE_AROMATHERAPY    312    //芳香治疗
#define    MOVE_FAKE_TEARS    313    //假哭
#define    MOVE_AIR_CUTTER    314    //空气利刃
#define    MOVE_OVERHEAT    315    //过热
#define    MOVE_ODOR_SLEUTH    316    //气味侦测
#define    MOVE_ROCK_TOMB    317    //岩石封锁
#define    MOVE_SILVER_WIND    318    //银色旋风
#define    MOVE_METAL_SOUND    319    //金属音
#define    MOVE_GRASS_WHISTLE    320    //草笛
#define    MOVE_TICKLE    321    //挠痒
#define    MOVE_COSMIC_POWER    322    //宇宙力量
#define    MOVE_WATER_SPOUT    323    //喷水
#define    MOVE_SIGNAL_BEAM    324    //信号光束
#define    MOVE_SHADOW_PUNCH    325    //暗影拳
#define    MOVE_EXTRASENSORY    326    //神通力
#define    MOVE_SKY_UPPERCUT    327    //冲天拳
#define    MOVE_SAND_TOMB    328    //流沙地狱
#define    MOVE_SHEER_COLD    329    //绝对零度
#define    MOVE_MUDDY_WATER    330    //浊流
#define    MOVE_BULLET_SEED    331    //种子机关枪
#define    MOVE_AERIAL_ACE    332    //燕返
#define    MOVE_ICICLE_SPEAR    333    //冰锥
#define    MOVE_IRON_DEFENSE    334    //铁壁
#define    MOVE_BLOCK    335    //挡路
#define    MOVE_HOWL    336    //长嚎
#define    MOVE_DRAGON_CLAW    337    //龙爪
#define    MOVE_FRENZY_PLANT    338    //疯狂植物
#define    MOVE_BULK_UP    339    //健美
#define    MOVE_BOUNCE    340    //弹跳
#define    MOVE_MUD_SHOT    341    //泥巴射击
#define    MOVE_POISON_TAIL    342    //毒尾
#define    MOVE_COVET    343    //渴望
#define    MOVE_VOLT_TACKLE    344    //伏特攻击
#define    MOVE_MAGICAL_LEAF    345    //魔法叶
#define    MOVE_WATER_SPORT    346    //玩水
#define    MOVE_CALM_MIND    347    //冥想
#define    MOVE_LEAF_BLADE    348    //叶刃
#define    MOVE_DRAGON_DANCE    349    //龙之舞
#define    MOVE_ROCK_BLAST    350    //岩石爆击
#define    MOVE_SHOCK_WAVE    351    //电击波
#define    MOVE_WATER_PULSE    352    //水之波动
#define    MOVE_DOOM_DESIRE    353    //破灭之愿
#define    MOVE_PSYCHO_BOOST    354    //精神突进
#define    MOVE_ROOST    355    //羽栖
#define    MOVE_GRAVITY    356    //重力
#define    MOVE_MIRACLE_EYE    357    //奇迹之眼
#define    MOVE_WAKEUP_SLAP    358    //唤醒巴掌
#define    MOVE_HAMMER_ARM    359    //臂锤
#define    MOVE_GYRO_BALL    360    //陀螺球
#define    MOVE_HEALING_WISH    361    //治愈之愿
#define    MOVE_BRINE    362    //盐水
#define    MOVE_NATURAL_GIFT    363    //自然之恩
#define    MOVE_FEINT    364    //佯攻
#define    MOVE_PLUCK    365    //啄食
#define    MOVE_TAILWIND    366    //顺风
#define    MOVE_ACUPRESSURE    367    //点穴
#define    MOVE_METAL_BURST    368    //金属爆炸
#define    MOVE_UTURN    369    //急速折返
#define    MOVE_CLOSE_COMBAT    370    //近身战
#define    MOVE_PAYBACK    371    //以牙还牙
#define    MOVE_ASSURANCE    372    //恶意追击
#define    MOVE_EMBARGO    373    //查封
#define    MOVE_FLING    374    //投掷
#define    MOVE_PSYCHO_SHIFT    375    //精神转移
#define    MOVE_TRUMP_CARD    376    //王牌
#define    MOVE_HEAL_BLOCK    377    //回复封锁
#define    MOVE_WRING_OUT    378    //绞紧
#define    MOVE_POWER_TRICK    379    //力量戏法
#define    MOVE_GASTRO_ACID    380    //胃液
#define    MOVE_LUCKY_CHANT    381    //幸运咒语
#define    MOVE_ME_FIRST    382    //抢先一步
#define    MOVE_COPYCAT    383    //仿效
#define    MOVE_POWER_SWAP    384    //力量互换
#define    MOVE_GUARD_SWAP    385    //防守互换
#define    MOVE_PUNISHMENT    386    //惩罚
#define    MOVE_LAST_RESORT    387    //珍藏
#define    MOVE_WORRY_SEED    388    //烦恼种子
#define    MOVE_SUCKER_PUNCH    389    //突袭
#define    MOVE_TOXIC_SPIKES    390    //毒菱
#define    MOVE_HEART_SWAP    391    //心灵互换
#define    MOVE_AQUA_RING    392    //水流环
#define    MOVE_MAGNET_RISE    393    //电磁飘浮
#define    MOVE_FLARE_BLITZ    394    //闪焰冲锋
#define    MOVE_FORCE_PALM    395    //发劲
#define    MOVE_AURA_SPHERE    396    //波导弹
#define    MOVE_ROCK_POLISH    397    //岩石打磨
#define    MOVE_POISON_JAB    398    //毒击
#define    MOVE_DARK_PULSE    399    //恶之波动
#define    MOVE_NIGHT_SLASH    400    //暗袭要害
#define    MOVE_AQUA_TAIL    401    //水流尾
#define    MOVE_SEED_BOMB    402    //种子炸弹
#define    MOVE_AIR_SLASH    403    //空气斩
#define    MOVE_XSCISSOR    404    //十字剪
#define    MOVE_BUG_BUZZ    405    //虫鸣
#define    MOVE_DRAGON_PULSE    406    //龙之波动
#define    MOVE_DRAGON_RUSH    407    //龙之俯冲
#define    MOVE_POWER_GEM    408    //力量宝石
#define    MOVE_DRAIN_PUNCH    409    //吸取拳
#define    MOVE_VACUUM_WAVE    410    //真空波
#define    MOVE_FOCUS_BLAST    411    //真气弹
#define    MOVE_ENERGY_BALL    412    //能量球
#define    MOVE_BRAVE_BIRD    413    //勇鸟猛攻
#define    MOVE_EARTH_POWER    414    //大地之力
#define    MOVE_SWITCHEROO    415    //掉包
#define    MOVE_GIGA_IMPACT    416    //终极冲击
#define    MOVE_NASTY_PLOT    417    //诡计
#define    MOVE_BULLET_PUNCH    418    //子弹拳
#define    MOVE_AVALANCHE    419    //雪崩
#define    MOVE_ICE_SHARD    420    //冰砾
#define    MOVE_SHADOW_CLAW    421    //暗影爪
#define    MOVE_THUNDER_FANG    422    //雷电牙
#define    MOVE_ICE_FANG    423    //冰冻牙
#define    MOVE_FIRE_FANG    424    //火焰牙
#define    MOVE_SHADOW_SNEAK    425    //影子偷袭
#define    MOVE_MUD_BOMB    426    //泥巴炸弹
#define    MOVE_PSYCHO_CUT    427    //精神利刃
#define    MOVE_ZEN_HEADBUTT    428    //意念头锤
#define    MOVE_MIRROR_SHOT    429    //镜光射击
#define    MOVE_FLASH_CANNON    430    //加农光炮
#define    MOVE_ROCK_CLIMB    431    //攀岩
#define    MOVE_DEFOG    432    //清除浓雾
#define    MOVE_TRICK_ROOM    433    //戏法空间
#define    MOVE_DRACO_METEOR    434    //流星群
#define    MOVE_DISCHARGE    435    //放电
#define    MOVE_LAVA_PLUME    436    //喷烟
#define    MOVE_LEAF_STORM    437    //飞叶风暴
#define    MOVE_POWER_WHIP    438    //强力鞭打
#define    MOVE_ROCK_WRECKER    439    //岩石炮
#define    MOVE_CROSS_POISON    440    //十字毒刃
#define    MOVE_GUNK_SHOT    441    //垃圾射击
#define    MOVE_IRON_HEAD    442    //铁头
#define    MOVE_MAGNET_BOMB    443    //磁铁炸弹
#define    MOVE_STONE_EDGE    444    //尖石攻击
#define    MOVE_CAPTIVATE    445    //诱惑
#define    MOVE_STEALTH_ROCK    446    //隐形岩
#define    MOVE_GRASS_KNOT    447    //打草结
#define    MOVE_CHATTER    448    //喋喋不休
#define    MOVE_JUDGMENT    449    //制裁光砾
#define    MOVE_BUG_BITE    450    //虫咬
#define    MOVE_CHARGE_BEAM    451    //充电光束
#define    MOVE_WOOD_HAMMER    452    //木槌
#define    MOVE_AQUA_JET    453    //水流喷射
#define    MOVE_ATTACK_ORDER    454    //攻击指令
#define    MOVE_DEFEND_ORDER    455    //防御指令
#define    MOVE_HEAL_ORDER    456    //回复指令
#define    MOVE_HEAD_SMASH    457    //双刃头锤
#define    MOVE_DOUBLE_HIT    458    //二连击
#define    MOVE_ROAR_OF_TIME    459    //时光咆哮
#define    MOVE_SPACIAL_REND    460    //亚空裂斩
#define    MOVE_LUNAR_DANCE    461    //新月舞
#define    MOVE_CRUSH_GRIP    462    //捏碎
#define    MOVE_MAGMA_STORM    463    //熔岩风暴
#define    MOVE_DARK_VOID    464    //暗黑洞
#define    MOVE_SEED_FLARE    465    //种子闪光
#define    MOVE_OMINOUS_WIND    466    //奇异之风
#define    MOVE_SHADOW_FORCE    467    //暗影潜袭
#define    MOVE_HONE_CLAWS    468    //磨爪
#define    MOVE_WIDE_GUARD    469    //广域防守
#define    MOVE_GUARD_SPLIT    470    //防守平分
#define    MOVE_POWER_SPLIT    471    //力量平分
#define    MOVE_WONDER_ROOM    472    //奇妙空间
#define    MOVE_PSYSHOCK    473    //精神冲击
#define    MOVE_VENOSHOCK    474    //毒液冲击
#define    MOVE_AUTOTOMIZE    475    //身体轻量化
#define    MOVE_RAGE_POWDER    476    //愤怒粉
#define    MOVE_TELEKINESIS    477    //意念移物
#define    MOVE_MAGIC_ROOM    478    //魔法空间
#define    MOVE_SMACK_DOWN    479    //击落
#define    MOVE_STORM_THROW    480    //山岚摔
#define    MOVE_FLAME_BURST    481    //烈焰溅射
#define    MOVE_SLUDGE_WAVE    482    //污泥波
#define    MOVE_QUIVER_DANCE    483    //蝶舞
#define    MOVE_HEAVY_SLAM    484    //重磅冲撞
#define    MOVE_SYNCHRONOISE    485    //同步干扰
#define    MOVE_ELECTRO_BALL    486    //电球
#define    MOVE_SOAK    487    //浸水
#define    MOVE_FLAME_CHARGE    488    //蓄能焰袭
#define    MOVE_COIL    489    //盘蜷
#define    MOVE_LOW_SWEEP    490    //下盘踢
#define    MOVE_ACID_SPRAY    491    //酸液炸弹
#define    MOVE_FOUL_PLAY    492    //欺诈
#define    MOVE_SIMPLE_BEAM    493    //单纯光束
#define    MOVE_ENTRAINMENT    494    //找伙伴
#define    MOVE_AFTER_YOU    495    //您先请
#define    MOVE_ROUND    496    //轮唱
#define    MOVE_ECHOED_VOICE    497    //回声
#define    MOVE_CHIP_AWAY    498    //逐步击破
#define    MOVE_CLEAR_SMOG    499    //清除之烟
#define    MOVE_STORED_POWER    500    //辅助力量
#define    MOVE_QUICK_GUARD    501    //快速防守
#define    MOVE_ALLY_SWITCH    502    //交换场地
#define    MOVE_SCALD    503    //热水
#define    MOVE_SHELL_SMASH    504    //破壳
#define    MOVE_HEAL_PULSE    505    //治愈波动
#define    MOVE_HEX    506    //祸不单行
#define    MOVE_SKY_DROP    507    //自由落体
#define    MOVE_SHIFT_GEAR    508    //换挡
#define    MOVE_CIRCLE_THROW    509    //巴投
#define    MOVE_INCINERATE    510    //烧尽
#define    MOVE_QUASH    511    //延后
#define    MOVE_ACROBATICS    512    //杂技
#define    MOVE_REFLECT_TYPE    513    //镜面属性
#define    MOVE_RETALIATE    514    //报仇
#define    MOVE_FINAL_GAMBIT    515    //搏命
#define    MOVE_BESTOW    516    //传递礼物
#define    MOVE_INFERNO    517    //炼狱
#define    MOVE_WATER_PLEDGE    518    //水之誓约
#define    MOVE_FIRE_PLEDGE    519    //火之誓约
#define    MOVE_GRASS_PLEDGE    520    //草之誓约
#define    MOVE_VOLT_SWITCH    521    //伏特替换
#define    MOVE_STRUGGLE_BUG    522    //虫之抵抗
#define    MOVE_BULLDOZE    523    //重踏
#define    MOVE_FROST_BREATH    524    //冰息
#define    MOVE_DRAGON_TAIL    525    //龙尾
#define    MOVE_WORK_UP    526    //自我激励
#define    MOVE_ELECTROWEB    527    //电网
#define    MOVE_WILD_CHARGE    528    //疯狂伏特
#define    MOVE_DRILL_RUN    529    //直冲钻
#define    MOVE_DUAL_CHOP    530    //二连劈
#define    MOVE_HEART_STAMP    531    //爱心印章
#define    MOVE_HORN_LEECH    532    //木角
#define    MOVE_SACRED_SWORD    533    //圣剑
#define    MOVE_RAZOR_SHELL    534    //贝壳刃
#define    MOVE_HEAT_CRASH    535    //高温重压
#define    MOVE_LEAF_TORNADO    536    //青草搅拌器
#define    MOVE_STEAMROLLER    537    //疯狂滚压
#define    MOVE_COTTON_GUARD    538    //棉花防守
#define    MOVE_NIGHT_DAZE    539    //暗黑爆破
#define    MOVE_PSYSTRIKE    540    //精神击破
#define    MOVE_TAIL_SLAP    541    //扫尾拍打
#define    MOVE_HURRICANE    542    //暴风
#define    MOVE_HEAD_CHARGE    543    //爆炸头突击
#define    MOVE_GEAR_GRIND    544    //齿轮飞盘
#define    MOVE_SEARING_SHOT    545    //火焰弹
#define    MOVE_TECHNO_BLAST    546    //高科技光炮
#define    MOVE_RELIC_SONG    547    //古老之歌
#define    MOVE_SECRET_SWORD    548    //神秘之剑
#define    MOVE_GLACIATE    549    //冰封世界
#define    MOVE_BOLT_STRIKE    550    //雷击
#define    MOVE_BLUE_FLARE    551    //青焰
#define    MOVE_FIERY_DANCE    552    //火之舞
#define    MOVE_FREEZE_SHOCK    553    //冰冻伏特
#define    MOVE_ICE_BURN    554    //极寒冷焰
#define    MOVE_SNARL    555    //大声咆哮
#define    MOVE_ICICLE_CRASH    556    //冰柱坠击
#define    MOVE_VCREATE    557    //Ｖ热焰
#define    MOVE_FUSION_FLARE    558    //交错火焰
#define    MOVE_FUSION_BOLT    559    //交错闪电
#define    MOVE_FLYING_PRESS    560    //飞身重压
#define    MOVE_MAT_BLOCK    561    //掀榻榻米
#define    MOVE_BELCH    562    //打嗝
#define    MOVE_ROTOTILLER    563    //耕地
#define    MOVE_STICKY_WEB    564    //黏黏网
#define    MOVE_FELL_STINGER    565    //致命针刺
#define    MOVE_PHANTOM_FORCE    566    //潜灵奇袭
#define    MOVE_TRICKORTREAT    567    //万圣夜
#define    MOVE_NOBLE_ROAR    568    //战吼
#define    MOVE_ION_DELUGE    569    //等离子浴
#define    MOVE_PARABOLIC_CHARGE    570    //抛物面充电
#define    MOVE_FORESTS_CURSE    571    //森林诅咒
#define    MOVE_PETAL_BLIZZARD    572    //落英缤纷
#define    MOVE_FREEZEDRY    573    //冷冻干燥
#define    MOVE_DISARMING_VOICE    574    //魅惑之声
#define    MOVE_PARTING_SHOT    575    //抛下狠话
#define    MOVE_TOPSYTURVY    576    //颠倒
#define    MOVE_DRAINING_KISS    577    //吸取之吻
#define    MOVE_CRAFTY_SHIELD    578    //戏法防守
#define    MOVE_FLOWER_SHIELD    579    //鲜花防守
#define    MOVE_GRASSY_TERRAIN    580    //青草场地
#define    MOVE_MISTY_TERRAIN    581    //薄雾场地
#define    MOVE_ELECTRIFY    582    //输电
#define    MOVE_PLAY_ROUGH    583    //嬉闹
#define    MOVE_FAIRY_WIND    584    //妖精之风
#define    MOVE_MOONBLAST    585    //月亮之力
#define    MOVE_BOOMBURST    586    //爆音波
#define    MOVE_FAIRY_LOCK    587    //妖精之锁
#define    MOVE_KINGS_SHIELD    588    //王者盾牌
#define    MOVE_PLAY_NICE    589    //和睦相处
#define    MOVE_CONFIDE    590    //密语
#define    MOVE_DIAMOND_STORM    591    //钻石风暴
#define    MOVE_STEAM_ERUPTION    592    //蒸汽爆炸
#define    MOVE_HYPERSPACE_HOLE    593    //异次元洞
#define    MOVE_WATER_SHURIKEN    594    //飞水手里剑
#define    MOVE_MYSTICAL_FIRE    595    //魔法火焰
#define    MOVE_SPIKY_SHIELD    596    //尖刺防守
#define    MOVE_AROMATIC_MIST    597    //芳香薄雾
#define    MOVE_EERIE_IMPULSE    598    //怪异电波
#define    MOVE_VENOM_DRENCH    599    //毒液陷阱
#define    MOVE_POWDER    600    //粉尘
#define    MOVE_GEOMANCY    601    //大地掌控
#define    MOVE_MAGNETIC_FLUX    602    //磁场操控
#define    MOVE_HAPPY_HOUR    603    //欢乐时光
#define    MOVE_ELECTRIC_TERRAIN    604    //电气场地
#define    MOVE_DAZZLING_GLEAM    605    //魔法闪耀
#define    MOVE_CELEBRATE    606    //庆祝
#define    MOVE_HOLD_HANDS    607    //牵手
#define    MOVE_BABYDOLL_EYES    608    //圆瞳
#define    MOVE_NUZZLE    609    //蹭蹭脸颊
#define    MOVE_HOLD_BACK    610    //手下留情
#define    MOVE_INFESTATION    611    //死缠烂打
#define    MOVE_POWERUP_PUNCH    612    //增强拳
#define    MOVE_OBLIVION_WING    613    //死亡之翼
#define    MOVE_THOUSAND_ARROWS    614    //千箭齐发
#define    MOVE_THOUSAND_WAVES    615    //千波激荡
#define    MOVE_LANDS_WRATH    616    //大地神力
#define    MOVE_LIGHT_OF_RUIN    617    //破灭之光
#define    MOVE_ORIGIN_PULSE    618    //根源波动
#define    MOVE_PRECIPICE_BLADES    619    //断崖之剑
#define    MOVE_DRAGON_ASCENT    620    //画龙点睛
#define    MOVE_HYPERSPACE_FURY    621    //异次元猛攻
#define    MOVE_SHORE_UP    622    //集沙
#define    MOVE_FIRST_IMPRESSION    623    //迎头一击
#define    MOVE_BANEFUL_BUNKER    624    //碉堡
#define    MOVE_SPIRIT_SHACKLE    625    //缝影
#define    MOVE_DARKEST_LARIAT    626    //ＤＤ金勾臂
#define    MOVE_SPARKLING_ARIA    627    //泡影的咏叹调
#define    MOVE_ICE_HAMMER    628    //冰锤
#define    MOVE_FLORAL_HEALING    629    //花疗
#define    MOVE_HIGH_HORSEPOWER    630    //十万马力
#define    MOVE_STRENGTH_SAP    631    //吸取力量
#define    MOVE_SOLAR_BLADE    632    //日光刃
#define    MOVE_LEAFAGE    633    //树叶
#define    MOVE_SPOTLIGHT    634    //聚光灯
#define    MOVE_TOXIC_THREAD    635    //毒丝
#define    MOVE_LASER_FOCUS    636    //磨砺
#define    MOVE_GEAR_UP    637    //辅助齿轮
#define    MOVE_THROAT_CHOP    638    //地狱突刺
#define    MOVE_POLLEN_PUFF    639    //花粉团
#define    MOVE_ANCHOR_SHOT    640    //掷锚
#define    MOVE_PSYCHIC_TERRAIN    641    //精神场地
#define    MOVE_LUNGE    642    //猛扑
#define    MOVE_FIRE_LASH    643    //火焰鞭
#define    MOVE_POWER_TRIP    644    //嚣张
#define    MOVE_BURN_UP    645    //燃尽
#define    MOVE_SPEED_SWAP    646    //速度互换
#define    MOVE_SMART_STRIKE    647    //修长之角
#define    MOVE_PURIFY    648    //净化
#define    MOVE_REVELATION_DANCE    649    //觉醒之舞
#define    MOVE_CORE_ENFORCER    650    //核心惩罚者
#define    MOVE_TROP_KICK    651    //热带踢
#define    MOVE_INSTRUCT    652    //号令
#define    MOVE_BEAK_BLAST    653    //鸟嘴加农炮
#define    MOVE_CLANGING_SCALES    654    //鳞片噪音
#define    MOVE_DRAGON_HAMMER    655    //龙锤
#define    MOVE_BRUTAL_SWING    656    //狂舞挥打
#define    MOVE_AURORA_VEIL    657    //极光幕
#define    MOVE_SHELL_TRAP    658    //陷阱甲壳
#define    MOVE_FLEUR_CANNON    659    //花朵加农炮
#define    MOVE_PSYCHIC_FANGS    660    //精神之牙
#define    MOVE_STOMPING_TANTRUM    661    //跺脚
#define    MOVE_SHADOW_BONE    662    //暗影之骨
#define    MOVE_ACCELEROCK    663    //冲岩
#define    MOVE_LIQUIDATION    664    //水流裂破
#define    MOVE_PRISMATIC_LASER    665    //棱镜镭射
#define    MOVE_SPECTRAL_THIEF    666    //暗影偷盗
#define    MOVE_SUNSTEEL_STRIKE    667    //流星闪冲
#define    MOVE_MOONGEIST_BEAM    668    //暗影之光
#define    MOVE_TEARFUL_LOOK    669    //泪眼汪汪
#define    MOVE_ZING_ZAP    670    //麻麻刺刺
#define    MOVE_NATURES_MADNESS    671    //自然之怒
#define    MOVE_MULTI_ATTACK    672    //多属性攻击
#define    MOVE_MIND_BLOWN    673    //惊爆大头
#define    MOVE_PLASMA_FISTS    674    //等离子闪电拳
#define    MOVE_PHOTON_GEYSER    675    //光子喷涌
#define    MOVE_Z_NORMAL_PHYS    676    //一般Ｚ究极无敌大冲撞
#define    MOVE_Z_NORMAL_SPEC    677    //一般Ｚ究极无敌大冲撞
#define    MOVE_Z_FIGHTING_PHYS    678    //格斗Ｚ全力无双激烈拳
#define    MOVE_Z_FIGHTING_SPEC    679    //格斗Ｚ全力无双激烈拳
#define    MOVE_Z_FLYING_PHYS    680    //飞行Ｚ极速俯冲轰烈撞
#define    MOVE_Z_FLYING_SPEC    681    //飞行Ｚ极速俯冲轰烈撞
#define    MOVE_Z_POISON_PHYS    682    //毒Ｚ强酸剧毒灭绝雨
#define    MOVE_Z_POISON_SPEC    683    //毒Ｚ强酸剧毒灭绝雨
#define    MOVE_Z_GROUND_PHYS    684    //地面Ｚ地隆啸天大终结
#define    MOVE_Z_GROUND_SPEC    685    //地面Ｚ地隆啸天大终结
#define    MOVE_Z_ROCK_PHYS    686    //岩石Ｚ毁天灭地巨岩坠
#define    MOVE_Z_ROCK_SPEC    687    //岩石Ｚ毁天灭地巨岩坠
#define    MOVE_Z_BUG_PHYS    688    //虫Ｚ绝对捕食回旋斩
#define    MOVE_Z_BUG_SPEC    689    //虫Ｚ绝对捕食回旋斩
#define    MOVE_Z_GHOST_PHYS    690    //幽灵Ｚ无尽暗夜之诱惑
#define    MOVE_Z_GHOST_SPEC    691    //幽灵Ｚ无尽暗夜之诱惑
#define    MOVE_Z_STEEL_PHYS    692    //钢Ｚ超绝螺旋连击
#define    MOVE_Z_STELL_SPEC    693    //钢Ｚ超绝螺旋连击
#define    MOVE_Z_FIRE_PHYS    694    //火Ｚ超强极限爆焰弹
#define    MOVE_Z_FIRE_SPEC    695    //火Ｚ超强极限爆焰弹
#define    MOVE_Z_WATER_PHYS    696    //水Ｚ超级水流大漩涡
#define    MOVE_Z_WATER_SPEC    697    //水Ｚ超级水流大漩涡
#define    MOVE_Z_GRASS_PHYS    698    //草Ｚ绚烂缤纷花怒放
#define    MOVE_Z_GRASS_SPEC    699    //草Ｚ绚烂缤纷花怒放
#define    MOVE_Z_ELECTRIC_PHYS    700    //电Ｚ终极伏特狂雷闪
#define    MOVE_Z_ELECTRIC_SPEC    701    //电Ｚ终极伏特狂雷闪
#define    MOVE_Z_PSYCHIC_PHYS    702    //超能力Ｚ至高精神破坏波
#define    MOVE_Z_PSYCHIC_SPEC    703    //超能力Ｚ至高精神破坏波
#define    MOVE_Z_ICE_PHYS    704    //冰Ｚ激狂大地万里冰
#define    MOVE_Z_ICE_SPEC    705    //冰Ｚ激狂大地万里冰
#define    MOVE_Z_DRAGON_PHYS    706    //龙Ｚ究极巨龙震天地
#define    MOVE_Z_DRAGON_SPEC    707    //龙Ｚ究极巨龙震天地
#define    MOVE_Z_DARK_PHYS    708    //恶Ｚ黑洞吞噬万物灭
#define    MOVE_Z_DARK_SPEC    709    //恶Ｚ黑洞吞噬万物灭
#define    MOVE_Z_FAIRY_PHYS    710    //妖精Ｚ可爱星星飞天撞
#define    MOVE_Z_FAIRY_SPEC    711    //妖精Ｚ可爱星星飞天撞
#define    MOVE_Z_CATASTROPIKA    712    //皮卡丘Ｚ皮卡皮卡必杀击
#define    MOVE_Z_DECIDUEYE    713    //狙射树枭Ｚ遮天蔽日暗影箭
#define    MOVE_Z_INCINEROAR    714    //炽焰咆哮虎Ｚ极恶飞跃粉碎击
#define    MOVE_Z_PRIMARINA    715    //西狮海壬Ｚ海神庄严交响乐
#define    MOVE_Z_TAPU    716    //卡璞Ｚ巨人卫士・阿罗拉
#define    MOVE_Z_MARSHADOW    717    //玛夏多Ｚ七星夺魂腿
#define    MOVE_Z_ALOLAN_RAICHU    718    //阿罗雷Ｚ驾雷驭电戏冲浪
#define    MOVE_Z_SNORLAX    719    //卡比兽Ｚ认真起来大爆击
#define    MOVE_Z_EEVEE    720    //伊布Ｚ九彩昇华齐聚顶
#define    MOVE_Z_MEW    721    //梦幻Ｚ起源超新星大爆炸
#define    MOVE_Z_ASH_PIKACHU    722    //智皮卡Ｚ千万伏特
#define    MOVE_Z_KOMMO_O    723    //杖尾鳞甲龙Ｚ炽魂热舞烈音爆
#define    MOVE_Z_LYCANROC    724    //鬃岩狼人Ｚ狼啸石牙飓风暴
#define    MOVE_Z_MIMIKYU    725    //谜拟ＱＺ亲密无间大乱揍
#define    MOVE_Z_SOLGALEO    726    //索尔迦雷欧Ｚ日光回旋下苍穹
#define    MOVE_Z_LUNALA    727    //露奈雅拉Ｚ月华飞溅落灵霄
#define    MOVE_Z_NECROZMA    728    //究极奈克洛Ｚ焚天灭世炽光爆
#define    MOVE_Z_ASH_GRENINJA    729    //忍者蛙Z
#define    MOVE_ZIPPY_ZAP 730        //电电加速
#define    MOVE_SPLISHY_SPLASH 731        //滔滔冲浪
#define    MOVE_FLOATY_FALL 732        //飘飘坠落
#define    MOVE_PIKA_PAPOW 733        //闪闪雷光
#define    MOVE_BOUNCY_BUBBLE 734        //活活气泡
#define    MOVE_BUZZY_BLITZ 735        //麻麻电击
#define    MOVE_SIZZLY_SLIDE 736        //熊熊火爆
#define    MOVE_GLITZY_GLOW 737        //哗哗气场
#define    MOVE_BADDY_BAD 738        //坏坏领域
#define    MOVE_SAPPY_SEED 739        //茁茁轰炸
#define    MOVE_FREEZY_FROST 740        //冰冰霜冻
#define    MOVE_SPARKLY_SWIRL 741        //亮亮风暴
#define    MOVE_VEEVEE_VOLLEY 742        //砰砰击破
#define    MOVE_DOUBLE_IRON_BASH 743        //钢拳双击
#define    MOVE_MAX_GUARD    744    //极巨防壁
#define    MOVE_DYNAMAX_CANNON    745    //极巨炮
#define    MOVE_SNIPE_SHOT    746    //狙击
#define    MOVE_JAW_LOCK    747    //紧咬不放
#define    MOVE_STUFF_CHEEKS    748    //大快朵颐
#define    MOVE_NO_RETREAT    749    //背水一战
#define    MOVE_TAR_SHOT    750    //沥青射击
#define    MOVE_MAGIC_POWDER    751    //魔法粉
#define    MOVE_DRAGON_DARTS    752    //龙箭
#define    MOVE_TEATIME    753    //茶会
#define    MOVE_OCTOLOCK    754    //蛸固
#define    MOVE_BOLT_BEAK    755    //电喙
#define    MOVE_FISHIOUS_REND    756    //鳃咬
#define    MOVE_COURT_CHANGE    757    //换场
#define    MOVE_MAX_FLARE    758    //极巨火爆
#define    MOVE_MAX_FLUTTERBY    759    //极巨虫蛊
#define    MOVE_MAX_LIGHTNING    760    //极巨闪电
#define    MOVE_MAX_STRIKE    761    //极巨攻击
#define    MOVE_MAX_KNUCKLE    762    //极巨拳斗
#define    MOVE_MAX_PHANTASM    763    //极巨幽魂
#define    MOVE_MAX_HAILSTORM    764    //极巨寒冰
#define    MOVE_MAX_OOZE    765    //极巨酸毒
#define    MOVE_MAX_GEYSER    766    //极巨水流
#define    MOVE_MAX_AIRSTREAM    767    //极巨飞冲
#define    MOVE_MAX_STARFALL    768    //极巨妖精
#define    MOVE_MAX_WYRMWIND    769    //极巨龙骑
#define    MOVE_MAX_MINDSTORM    770    //极巨超能
#define    MOVE_MAX_ROCKFALL    771    //极巨岩石
#define    MOVE_MAX_QUAKE    772    //极巨大地
#define    MOVE_MAX_DARKNESS    773    //极巨恶霸
#define    MOVE_MAX_OVERGROWTH    774    //极巨草原
#define    MOVE_MAX_STEELSPIKE    775    //极巨钢铁
#define    MOVE_CLANGOROUS_SOUL    776    //魂舞烈音爆
#define    MOVE_BODY_PRESS    777    //扑击
#define    MOVE_DECORATE    778    //装饰
#define    MOVE_DRUM_BEATING    779    //鼓击
#define    MOVE_SNAP_TRAP    780    //捕兽夹
#define    MOVE_PYRO_BALL    781    //火焰球
#define    MOVE_BEHEMOTH_BLADE    782    //巨兽斩
#define    MOVE_BEHEMOTH_BASH    783    //巨兽弹
#define    MOVE_AURA_WHEEL    784    //气场轮
#define    MOVE_BREAKING_SWIPE    785    //广域破坏
#define    MOVE_BRANCH_POKE    786    //木枝突刺
#define    MOVE_OVERDRIVE    787    //破音
#define    MOVE_APPLE_ACID    788    //苹果酸
#define    MOVE_GRAV_APPLE    789    //万有引力
#define    MOVE_SPIRIT_BREAK    790    //灵魂冲击
#define    MOVE_STRANGE_STEAM    791    //神奇蒸汽
#define    MOVE_LIFE_DEW    792    //生命水滴
#define    MOVE_OBSTRUCT    793    //拦堵
#define    MOVE_FALSE_SURRENDER    794    //假跪真撞
#define    MOVE_METEOR_ASSAULT    795    //流星突击
#define    MOVE_ETERNABEAM    796    //无极光束
#define    MOVE_STEEL_BEAM    797    //铁蹄光线


#endif /* MOVE_IDS_H */
