//
// Created by ilove on 2018/8/6.
//
#include "defines/pokes.h"
#include "defines/moves.h"

const unsigned short egg_moves[] = {
		POKE_BULBASAUR + 20000, MOVE_GRASS_WHISTLE, MOVE_LEAF_STORM, MOVE_PETAL_DANCE, MOVE_SKULL_BASH, MOVE_MAGICAL_LEAF, MOVE_POWER_WHIP, MOVE_GRASSY_TERRAIN, MOVE_CHARM, MOVE_AMNESIA, MOVE_ENDURE, MOVE_SLUDGE, MOVE_INGRAIN, MOVE_GIGA_DRAIN, MOVE_NATURE_POWER, MOVE_CURSE,
		/*0001 ÃîÍÜÖÖ×Ó*/

		POKE_CHARMANDER + 20000, MOVE_BELLY_DRUM, MOVE_METAL_CLAW, MOVE_AIR_CUTTER, MOVE_DRAGON_PULSE, MOVE_DRAGON_RUSH, MOVE_DRAGON_DANCE, MOVE_OUTRAGE, MOVE_FLARE_BLITZ, MOVE_COUNTER, MOVE_BEAT_UP, MOVE_CRUNCH, MOVE_BITE, MOVE_ANCIENT_POWER, MOVE_FOCUS_PUNCH,
		/*0004 Ð¡»ðÁú*/

		POKE_SQUIRTLE + 20000, MOVE_MIST, MOVE_AURA_SPHERE, MOVE_YAWN, MOVE_HAZE, MOVE_REFRESH, MOVE_FAKE_OUT, MOVE_MIRROR_COAT, MOVE_DRAGON_PULSE, MOVE_WATER_SPOUT, MOVE_FORESIGHT, MOVE_AQUA_RING, MOVE_AQUA_JET, MOVE_MUD_SPORT, MOVE_BRINE, MOVE_FLAIL, MOVE_MUDDY_WATER,
		/*0007 ½ÜÄá¹ê*/

		POKE_PIDGEY + 20000, MOVE_UPROAR, MOVE_FEINT_ATTACK, MOVE_STEEL_WING, MOVE_AIR_CUTTER, MOVE_AIR_SLASH, MOVE_DEFOG, MOVE_FORESIGHT, MOVE_BRAVE_BIRD, MOVE_PURSUIT,
		/*0010 ²¨²¨*/

		POKE_RATATTA + 20000, MOVE_REVENGE, MOVE_FINAL_GAMBIT, MOVE_UPROAR, MOVE_SCREECH, MOVE_FLAME_WHEEL, MOVE_FURY_SWIPES, MOVE_REVERSAL, MOVE_ME_FIRST, MOVE_COUNTER, MOVE_BITE, MOVE_LAST_RESORT,
		/*0013 Ð¡À­´ï*/

		POKE_SPEARROW + 20000, MOVE_UPROAR, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_QUICK_ATTACK, MOVE_STEEL_WING, MOVE_SCARY_FACE, MOVE_ASTONISH, MOVE_TRI_ATTACK, MOVE_SKY_ATTACK, MOVE_RAZOR_WIND, MOVE_FEATHER_DANCE,
		/*0015 ÁÒÈ¸*/

		POKE_EKANS + 20000, MOVE_SWITCHEROO, MOVE_DISABLE, MOVE_POISON_TAIL, MOVE_SCARY_FACE, MOVE_POISON_FANG, MOVE_SNATCH, MOVE_SLAM, MOVE_IRON_TAIL, MOVE_SUCKER_PUNCH, MOVE_BEAT_UP, MOVE_SPITE, MOVE_PURSUIT,
		/*0017 °¢°ØÉß*/

		POKE_SANDSHREW + 20000, MOVE_NIGHT_SLASH, MOVE_RAPID_SPIN, MOVE_ROTOTILLER, MOVE_METAL_CLAW, MOVE_HONE_CLAWS, MOVE_MUD_SHOT, MOVE_ROCK_CLIMB, MOVE_COUNTER, MOVE_CRUSH_CLAW, MOVE_ENDURE, MOVE_CHIP_AWAY, MOVE_FLAIL,
		/*001B ´©É½Êó*/

		POKE_NIDORANFEMALE + 20000, MOVE_SUPERSONIC, MOVE_DISABLE, MOVE_POISON_TAIL, MOVE_VENOM_DRENCH, MOVE_SKULL_BASH, MOVE_FOCUS_ENERGY, MOVE_TAKE_DOWN, MOVE_CHARM, MOVE_COUNTER, MOVE_IRON_TAIL, MOVE_ENDURE, MOVE_BEAT_UP, MOVE_CHIP_AWAY, MOVE_PURSUIT,
		/*001D Äá¶àÀ¼*/

		POKE_NIDORANMALE + 20000, MOVE_SUPERSONIC, MOVE_DISABLE, MOVE_POISON_TAIL, MOVE_VENOM_DRENCH, MOVE_TAKE_DOWN, MOVE_CONFUSION, MOVE_COUNTER, MOVE_HEAD_SMASH, MOVE_AMNESIA, MOVE_IRON_TAIL, MOVE_ENDURE, MOVE_SUCKER_PUNCH, MOVE_BEAT_UP, MOVE_CHIP_AWAY,
		/*0020 Äá¶àÀÊ*/

		POKE_VULPIX + 20000, MOVE_FEINT_ATTACK, MOVE_HYPNOSIS, MOVE_DISABLE, MOVE_HEX, MOVE_POWER_SWAP, MOVE_SECRET_POWER, MOVE_HEAT_WAVE, MOVE_TAIL_SLAP, MOVE_FLARE_BLITZ, MOVE_EXTRASENSORY, MOVE_CAPTIVATE, MOVE_SPITE, MOVE_HOWL, MOVE_FLAIL,
		/*0025 ÁùÎ²*/

		POKE_ZUBAT + 20000, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_HYPNOSIS, MOVE_QUICK_ATTACK, MOVE_VENOM_DRENCH, MOVE_STEEL_WING, MOVE_NASTY_PLOT, MOVE_GUST, MOVE_DEFOG, MOVE_ZEN_HEADBUTT, MOVE_BRAVE_BIRD, MOVE_GIGA_DRAIN, MOVE_PURSUIT, MOVE_CURSE,
		/*0029 ³¬Òôòð*/

		POKE_ODDISH + 20000, MOVE_RAZOR_LEAF, MOVE_SYNTHESIS, MOVE_SECRET_POWER, MOVE_TICKLE, MOVE_AFTER_YOU, MOVE_CHARM, MOVE_STRENGTH_SAP, MOVE_TEETER_DANCE, MOVE_INGRAIN, MOVE_FLAIL, MOVE_NATURE_POWER,
		/*002B ×ßÂ·²Ý*/

		POKE_PARAS + 20000, MOVE_BUG_BITE, MOVE_SCREECH, MOVE_AGILITY, MOVE_ROTOTILLER, MOVE_WIDE_GUARD, MOVE_PSYBEAM, MOVE_LEECH_SEED, MOVE_METAL_CLAW, MOVE_GRASSY_TERRAIN, MOVE_CROSS_POISON, MOVE_COUNTER, MOVE_SWEET_SCENT, MOVE_FELL_STINGER, MOVE_FLAIL, MOVE_PURSUIT, MOVE_NATURAL_GIFT,
		/*002E ÅÉÀ­Ë¹*/

		POKE_VENONAT + 20000, MOVE_MORNING_SUN, MOVE_BUG_BITE, MOVE_SCREECH, MOVE_TOXIC_SPIKES, MOVE_RAGE_POWDER, MOVE_AGILITY, MOVE_BATON_PASS, MOVE_SECRET_POWER, MOVE_SKILL_SWAP, MOVE_SIGNAL_BEAM, MOVE_GIGA_DRAIN,
		/*0030 Ã«Çò*/

		POKE_DIGLETT + 20000, MOVE_FINAL_GAMBIT, MOVE_UPROAR, MOVE_FEINT_ATTACK, MOVE_SCREECH, MOVE_ASTONISH, MOVE_MEMENTO, MOVE_MUD_BOMB, MOVE_REVERSAL, MOVE_ENDURE, MOVE_HEADBUTT, MOVE_BEAT_UP, MOVE_ANCIENT_POWER, MOVE_PURSUIT,
		/*0032 µØÊó*/

		POKE_MEOWTH + 20000, MOVE_PUNISHMENT, MOVE_HYPNOSIS, MOVE_ASSIST, MOVE_FOUL_PLAY, MOVE_ODOR_SLEUTH, MOVE_SNATCH, MOVE_CHARM, MOVE_AMNESIA, MOVE_IRON_TAIL, MOVE_TAIL_WHIP, MOVE_SPITE, MOVE_LAST_RESORT, MOVE_FLAIL,
		/*0034 ß÷ß÷*/

		POKE_PSYDUCK + 20000, MOVE_HYPNOSIS, MOVE_SIMPLE_BEAM, MOVE_YAWN, MOVE_PSYBEAM, MOVE_REFRESH, MOVE_SLEEP_TALK, MOVE_SECRET_POWER, MOVE_MUD_BOMB, MOVE_CONFUSE_RAY, MOVE_CLEAR_SMOG, MOVE_CROSS_CHOP, MOVE_FORESIGHT, MOVE_SYNCHRONOISE, MOVE_FUTURE_SIGHT, MOVE_ENCORE,
		/*0036 ¿É´ïÑ¼*/

		POKE_MANKEY + 20000, MOVE_NIGHT_SLASH, MOVE_REVENGE, MOVE_CLOSE_COMBAT, MOVE_SLEEP_TALK, MOVE_REVERSAL, MOVE_SMELLING_SALTS, MOVE_FORESIGHT, MOVE_COUNTER, MOVE_BEAT_UP, MOVE_POWER_TRIP, MOVE_MEDITATE, MOVE_ENCORE, MOVE_FOCUS_PUNCH,
		/*0038 ºï¹Ö*/

		POKE_GROWLITHE + 20000, MOVE_MORNING_SUN, MOVE_THRASH, MOVE_DOUBLE_KICK, MOVE_FIRE_SPIN, MOVE_CLOSE_COMBAT, MOVE_COVET, MOVE_BURN_UP, MOVE_HEAT_WAVE, MOVE_FLARE_BLITZ, MOVE_DOUBLEEDGE, MOVE_BODY_SLAM, MOVE_IRON_TAIL, MOVE_CRUNCH, MOVE_HOWL,
		/*003A ¿¨µÙ¹·*/

		POKE_POLIWAG + 20000, MOVE_MIST, MOVE_ICE_BALL, MOVE_HAZE, MOVE_REFRESH, MOVE_ENDEAVOR, MOVE_MUD_SHOT, MOVE_BUBBLE_BEAM, MOVE_WATER_PULSE, MOVE_ENDURE, MOVE_WATER_SPORT, MOVE_MIND_READER, MOVE_SPLASH, MOVE_ENCORE,
		/*003C ÎÃÏãòòò½*/

		POKE_ABRA + 20000, MOVE_ICE_PUNCH, MOVE_GUARD_SWAP, MOVE_GUARD_SPLIT, MOVE_FIRE_PUNCH, MOVE_ALLY_SWITCH, MOVE_PSYCHIC_TERRAIN, MOVE_PSYCHO_SHIFT, MOVE_THUNDER_PUNCH, MOVE_POWER_TRICK, MOVE_KNOCK_OFF, MOVE_BARRIER, MOVE_SKILL_SWAP, MOVE_ENCORE,
		/*003F ¿­Î÷*/

		POKE_MACHOP + 20000, MOVE_ICE_PUNCH, MOVE_ROLLING_KICK, MOVE_FIRE_PUNCH, MOVE_CLOSE_COMBAT, MOVE_QUICK_GUARD, MOVE_THUNDER_PUNCH, MOVE_POWER_TRICK, MOVE_TICKLE, MOVE_KNOCK_OFF, MOVE_SMELLING_SALTS, MOVE_COUNTER, MOVE_MEDITATE, MOVE_ENCORE, MOVE_HEAVY_SLAM, MOVE_BULLET_PUNCH,
		/*0042 ÍóÁ¦*/

		POKE_BELLSPROUT + 20000, MOVE_BELCH, MOVE_WORRY_SEED, MOVE_SYNTHESIS, MOVE_MAGICAL_LEAF, MOVE_TICKLE, MOVE_WEATHER_BALL, MOVE_POWER_WHIP, MOVE_CLEAR_SMOG, MOVE_ACID_SPRAY, MOVE_STRENGTH_SAP, MOVE_LEECH_LIFE, MOVE_ENCORE, MOVE_INGRAIN, MOVE_GIGA_DRAIN, MOVE_BULLET_SEED, MOVE_NATURAL_GIFT,
		/*0045 À®°ÈÑ¿*/

		POKE_TENTACOOL + 20000, MOVE_ACUPRESSURE, MOVE_RAPID_SPIN, MOVE_HAZE, MOVE_AURORA_BEAM, MOVE_MIRROR_COAT, MOVE_TICKLE, MOVE_KNOCK_OFF, MOVE_BUBBLE, MOVE_CONFUSE_RAY, MOVE_AQUA_RING, MOVE_MUDDY_WATER,
		/*0048 Âêè§Ë®Ä¸*/

		POKE_GEODUDE + 20000, MOVE_MEGA_PUNCH, MOVE_HAMMER_ARM, MOVE_BLOCK, MOVE_WIDE_GUARD, MOVE_ROCK_CLIMB, MOVE_AUTOTOMIZE, MOVE_ENDURE, MOVE_FOCUS_PUNCH, MOVE_FLAIL, MOVE_CURSE,
		/*004A Ð¡È­Ê¯*/

		POKE_PONYTA + 20000, MOVE_MORNING_SUN, MOVE_HYPNOSIS, MOVE_THRASH, MOVE_DOUBLE_KICK, MOVE_FLAME_WHEEL, MOVE_ALLY_SWITCH, MOVE_HORN_DRILL, MOVE_CHARM, MOVE_DOUBLEEDGE, MOVE_HIGH_HORSEPOWER, MOVE_LOW_KICK, MOVE_CAPTIVATE,
		/*004D Ð¡»ðÂí*/

		POKE_SLOWPOKE + 20000, MOVE_STOMP, MOVE_BELCH, MOVE_SNORE, MOVE_BLOCK, MOVE_BELLY_DRUM, MOVE_SLEEP_TALK, MOVE_WONDER_ROOM, MOVE_ME_FIRST, MOVE_MUD_SPORT, MOVE_ZEN_HEADBUTT, MOVE_FUTURE_SIGHT,
		/*004F ´ô´ôÊÞ*/

		POKE_FARFETCHD + 20000, MOVE_REVENGE, MOVE_FINAL_GAMBIT, MOVE_SIMPLE_BEAM, MOVE_QUICK_ATTACK, MOVE_STEEL_WING, MOVE_GUST, MOVE_FORESIGHT, MOVE_TRUMP_CARD, MOVE_LEAF_BLADE, MOVE_MIRROR_MOVE, MOVE_FIRST_IMPRESSION, MOVE_FEATHER_DANCE, MOVE_ROOST, MOVE_MUDSLAP, MOVE_FLAIL, MOVE_CURSE,
		/*0053 ´ó´ÐÑ¼*/

		POKE_DODUO + 20000, MOVE_SUPERSONIC, MOVE_FEINT_ATTACK, MOVE_QUICK_ATTACK, MOVE_ASSURANCE, MOVE_HAZE, MOVE_ENDEAVOR, MOVE_MIRROR_MOVE, MOVE_BRAVE_BIRD, MOVE_FLAIL, MOVE_NATURAL_GIFT,
		/*0054 à½à½*/

		POKE_SEEL + 20000, MOVE_ICICLE_SPEAR, MOVE_BELCH, MOVE_DISABLE, MOVE_FAKE_OUT, MOVE_HORN_DRILL, MOVE_SLEEP_TALK, MOVE_PERISH_SONG, MOVE_SPIT_UP, MOVE_LICK, MOVE_SLAM, MOVE_WATER_PULSE, MOVE_IRON_TAIL, MOVE_SWALLOW, MOVE_SIGNAL_BEAM, MOVE_STOCKPILE, MOVE_ENTRAINMENT,
		/*0056 Ð¡º£Ê¨*/

		POKE_GRIMER + 20000, MOVE_SHADOW_PUNCH, MOVE_IMPRISON, MOVE_SCARY_FACE, MOVE_MEAN_LOOK, MOVE_HAZE, MOVE_SPIT_UP, MOVE_LICK, MOVE_ACID_SPRAY, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_SHADOW_SNEAK, MOVE_OBLIVION_WING, MOVE_CURSE,
		/*0058 ³ôÄà*/

		POKE_SHELLDER + 20000, MOVE_ICICLE_SPEAR, MOVE_SCREECH, MOVE_RAPID_SPIN, MOVE_TAKE_DOWN, MOVE_MUD_SHOT, MOVE_BUBBLE_BEAM, MOVE_BARRIER, MOVE_TWINEEDLE, MOVE_AQUA_RING, MOVE_WATER_PULSE, MOVE_AVALANCHE, MOVE_ROCK_BLAST,
		/*005A ´óÉà±´*/

		POKE_GASTLY + 20000, MOVE_ICE_PUNCH, MOVE_DISABLE, MOVE_SCARY_FACE, MOVE_HAZE, MOVE_FIRE_PUNCH, MOVE_ASTONISH, MOVE_PSYWAVE, MOVE_REFLECT_TYPE, MOVE_THUNDER_PUNCH, MOVE_PERISH_SONG, MOVE_CLEAR_SMOG, MOVE_GRUDGE, MOVE_SMOG,
		/*005C ¹íË¹*/

		POKE_ONIX + 20000, MOVE_DEFENSE_CURL, MOVE_BLOCK, MOVE_ROTOTILLER, MOVE_WIDE_GUARD, MOVE_ROLLOUT, MOVE_ROCK_CLIMB, MOVE_ROCK_BLAST, MOVE_STEALTH_ROCK, MOVE_HEAVY_SLAM, MOVE_FLAIL,
		/*005F ´óÑÒÉß*/

		POKE_DROWZEE + 20000, MOVE_ROLE_PLAY, MOVE_ICE_PUNCH, MOVE_FLATTER, MOVE_GUARD_SWAP, MOVE_NASTY_PLOT, MOVE_FIRE_PUNCH, MOVE_ASSIST, MOVE_PSYCHIC_TERRAIN, MOVE_PSYCHO_CUT, MOVE_THUNDER_PUNCH, MOVE_POWER_SPLIT, MOVE_SECRET_POWER, MOVE_BARRIER, MOVE_SKILL_SWAP,
		/*0060 ´ßÃßõø*/

		POKE_KRABBY + 20000, MOVE_AGILITY, MOVE_HAZE, MOVE_ALLY_SWITCH, MOVE_TICKLE, MOVE_KNOCK_OFF, MOVE_BIDE, MOVE_SLAM, MOVE_AMNESIA, MOVE_ENDURE, MOVE_ANCIENT_POWER, MOVE_CHIP_AWAY, MOVE_FLAIL,
		/*0062 ´óÇ¯Ð·*/

		POKE_EXEGGCUTE + 20000, MOVE_BLOCK, MOVE_LEAF_STORM, MOVE_SYNTHESIS, MOVE_POWER_SWAP, MOVE_GRASSY_TERRAIN, MOVE_SKILL_SWAP, MOVE_LUCKY_CHANT, MOVE_ANCIENT_POWER, MOVE_MOONLIGHT, MOVE_INGRAIN, MOVE_GIGA_DRAIN, MOVE_NATURAL_GIFT, MOVE_NATURE_POWER, MOVE_CURSE,
		/*0066 µ°µ°*/

		POKE_CUBONE + 20000, MOVE_SCREECH, MOVE_DOUBLE_KICK, MOVE_BELLY_DRUM, MOVE_SKULL_BASH, MOVE_DETECT, MOVE_PERISH_SONG, MOVE_IRON_HEAD, MOVE_ENDURE, MOVE_ANCIENT_POWER, MOVE_CHIP_AWAY, MOVE_CURSE,
		/*0068 ¿¨À­¿¨À­*/

		POKE_LICKITUNG + 20000, MOVE_HAMMER_ARM, MOVE_BELCH, MOVE_SNORE, MOVE_THRASH, MOVE_BELLY_DRUM, MOVE_SLEEP_TALK, MOVE_SMELLING_SALTS, MOVE_AMNESIA, MOVE_BODY_SLAM, MOVE_ZEN_HEADBUTT, MOVE_MAGNITUDE, MOVE_MUDDY_WATER, MOVE_CURSE,
		/*006C ´óÉàÍ·*/

		POKE_KOFFING + 20000, MOVE_SCREECH, MOVE_TOXIC_SPIKES, MOVE_VENOM_DRENCH, MOVE_PAIN_SPLIT, MOVE_PSYBEAM, MOVE_PSYWAVE, MOVE_SPIT_UP, MOVE_DESTINY_BOND, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_SPITE, MOVE_GRUDGE, MOVE_CURSE,
		/*006D ÍßË¹µ¯*/

		POKE_RHYHORN + 20000, MOVE_ICE_FANG, MOVE_GUARD_SPLIT, MOVE_ROTOTILLER, MOVE_SKULL_BASH, MOVE_FIRE_FANG, MOVE_METAL_BURST, MOVE_THUNDER_FANG, MOVE_DRAGON_RUSH, MOVE_ROCK_CLIMB, MOVE_REVERSAL, MOVE_COUNTER, MOVE_CRUSH_CLAW, MOVE_IRON_TAIL, MOVE_CRUNCH, MOVE_MAGNITUDE, MOVE_CURSE,
		/*006F ¶À½ÇÏ¬Å£*/

		POKE_CHANSEY + 20000, MOVE_HELPING_HAND, MOVE_SEISMIC_TOSS, MOVE_AROMATHERAPY, MOVE_METRONOME, MOVE_PRESENT, MOVE_MUD_BOMB, MOVE_COUNTER, MOVE_ENDURE, MOVE_LAST_RESORT, MOVE_HEAL_BELL, MOVE_GRAVITY, MOVE_NATURAL_GIFT,
		/*0071 ¼ªÀûµ°*/

		POKE_TANGELA + 20000, MOVE_MEGA_DRAIN, MOVE_LEAF_STORM, MOVE_RAGE_POWDER, MOVE_WAKEUP_SLAP, MOVE_LEECH_SEED, MOVE_POWER_SWAP, MOVE_ENDEAVOR, MOVE_CONFUSION, MOVE_AMNESIA, MOVE_GIGA_DRAIN, MOVE_FLAIL, MOVE_NATURAL_GIFT, MOVE_NATURE_POWER,
		/*0072 ÂûÌÙ¹Ö*/

		POKE_KANGASKHAN + 20000, MOVE_CIRCLE_THROW, MOVE_HAMMER_ARM, MOVE_STOMP, MOVE_UPROAR, MOVE_DISABLE, MOVE_FOCUS_ENERGY, MOVE_ENDEAVOR, MOVE_DOUBLEEDGE, MOVE_FORESIGHT, MOVE_COUNTER, MOVE_CRUSH_CLAW, MOVE_TRUMP_CARD, MOVE_FOCUS_PUNCH,
		/*0073 ´üÊÞ*/

		POKE_HORSEA + 20000, MOVE_DISABLE, MOVE_AURORA_BEAM, MOVE_DRAGON_BREATH, MOVE_DRAGON_RAGE, MOVE_OUTRAGE, MOVE_CLEAR_SMOG, MOVE_WATER_PULSE, MOVE_SIGNAL_BEAM, MOVE_RAZOR_WIND, MOVE_SPLASH, MOVE_OCTAZOOKA, MOVE_FLAIL, MOVE_MUDDY_WATER,
		/*0074 Ä«º£Âí*/

		POKE_GOLDEEN + 20000, MOVE_HAZE, MOVE_PSYBEAM, MOVE_SKULL_BASH, MOVE_SLEEP_TALK, MOVE_MUD_SHOT, MOVE_AQUA_TAIL, MOVE_HYDRO_PUMP, MOVE_BODY_SLAM, MOVE_MUD_SPORT, MOVE_SIGNAL_BEAM, MOVE_MUDSLAP,
		/*0076 ½Ç½ðÓã*/

		POKE_MRMIME + 20000, MOVE_ICY_WIND, MOVE_HYPNOSIS, MOVE_NASTY_PLOT, MOVE_WAKEUP_SLAP, MOVE_FAKE_OUT, MOVE_PSYCHIC_TERRAIN, MOVE_POWER_SPLIT, MOVE_MIMIC, MOVE_MAGIC_ROOM, MOVE_CONFUSE_RAY, MOVE_CHARM, MOVE_TRICK, MOVE_TEETER_DANCE, MOVE_FUTURE_SIGHT, MOVE_HEALING_WISH,
		/*007A Ä§Ç½ÈËÅ¼*/

		POKE_SCYTHER + 20000, MOVE_NIGHT_SLASH, MOVE_BUG_BUZZ, MOVE_STEEL_WING, MOVE_BATON_PASS, MOVE_QUICK_GUARD, MOVE_REVERSAL, MOVE_DEFOG, MOVE_COUNTER, MOVE_ENDURE, MOVE_RAZOR_WIND, MOVE_SILVER_WIND,
		/*007B ·ÉÌìó«òë*/

		POKE_PINSIR + 20000, MOVE_BUG_BITE, MOVE_FEINT_ATTACK, MOVE_QUICK_ATTACK, MOVE_CLOSE_COMBAT, MOVE_FURY_ATTACK, MOVE_SUPERPOWER, MOVE_ME_FIRST, MOVE_FEINT, MOVE_FLAIL,
		/*007F ¿­ÂÞË¹*/

		POKE_LAPRAS + 20000, MOVE_WHIRLPOOL, MOVE_FISSURE, MOVE_REFRESH, MOVE_HORN_DRILL, MOVE_FREEZEDRY, MOVE_DRAGON_PULSE, MOVE_DRAGON_DANCE, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_FORESIGHT, MOVE_AVALANCHE, MOVE_FUTURE_SIGHT, MOVE_ANCIENT_POWER, MOVE_CURSE,
		/*0083 À­ÆÕÀ­Ë¹*/

		POKE_EEVEE + 20000, MOVE_STORED_POWER, MOVE_YAWN, MOVE_FAKE_TEARS, MOVE_DETECT, MOVE_COVET, MOVE_TICKLE, MOVE_WISH, MOVE_CHARM, MOVE_ENDURE, MOVE_SYNCHRONOISE, MOVE_CAPTIVATE, MOVE_FLAIL, MOVE_NATURAL_GIFT, MOVE_CURSE,
		/*0085 ÒÁ²¼*/

		POKE_OMANYTE + 20000, MOVE_SUPERSONIC, MOVE_WHIRLPOOL, MOVE_TOXIC_SPIKES, MOVE_HAZE, MOVE_AURORA_BEAM, MOVE_WRING_OUT, MOVE_REFLECT_TYPE, MOVE_KNOCK_OFF, MOVE_BUBBLE_BEAM, MOVE_BIDE, MOVE_SPIKES, MOVE_SLAM, MOVE_WATER_PULSE, MOVE_MUDDY_WATER,
		/*008A ¾ÕÊ¯ÊÞ*/

		POKE_KABUTO + 20000, MOVE_ICY_WIND, MOVE_SCREECH, MOVE_RAPID_SPIN, MOVE_AURORA_BEAM, MOVE_TAKE_DOWN, MOVE_MUD_SHOT, MOVE_KNOCK_OFF, MOVE_BUBBLE_BEAM, MOVE_CONFUSE_RAY, MOVE_FORESIGHT, MOVE_GIGA_DRAIN, MOVE_FLAIL,
		/*008C »¯Ê¯¿ø*/

		POKE_AERODACTYL + 20000, MOVE_WHIRLWIND, MOVE_ASSURANCE, MOVE_STEEL_WING, MOVE_WIDE_GUARD, MOVE_DRAGON_BREATH, MOVE_FORESIGHT, MOVE_TAILWIND, MOVE_ROOST, MOVE_PURSUIT, MOVE_CURSE,
		/*008E »¯Ê¯ÒíÁú*/

		POKE_SNORLAX + 20000, MOVE_WHIRLWIND, MOVE_BELCH, MOVE_FISSURE, MOVE_AFTER_YOU, MOVE_CHARM, MOVE_LICK, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_ZEN_HEADBUTT, MOVE_OBLIVION_WING, MOVE_PURSUIT, MOVE_SELFDESTRUCT, MOVE_NATURAL_GIFT, MOVE_CURSE,
		/*008F ¿¨±ÈÊÞ*/

		POKE_DRATINI + 20000, MOVE_MIST, MOVE_SUPERSONIC, MOVE_HAZE, MOVE_DRAGON_BREATH, MOVE_DRAGON_PULSE, MOVE_DRAGON_RUSH, MOVE_DRAGON_DANCE, MOVE_EXTREME_SPEED, MOVE_AQUA_JET, MOVE_WATER_PULSE, MOVE_IRON_TAIL,
		/*0093 ÃÔÄãÁú*/

		POKE_CHIKORITA + 20000, MOVE_GRASS_WHISTLE, MOVE_AROMATHERAPY, MOVE_LEAF_STORM, MOVE_REFRESH, MOVE_LEECH_SEED, MOVE_WRING_OUT, MOVE_GRASSY_TERRAIN, MOVE_COUNTER, MOVE_BODY_SLAM, MOVE_VINE_WHIP, MOVE_ANCIENT_POWER, MOVE_INGRAIN, MOVE_HEAL_PULSE, MOVE_FLAIL, MOVE_NATURE_POWER,
		/*0098 ¾Õ²ÝÒ¶*/

		POKE_CYNDAQUIL + 20000, MOVE_THRASH, MOVE_QUICK_ATTACK, MOVE_DOUBLE_KICK, MOVE_COVET, MOVE_FLAME_BURST, MOVE_FURY_SWIPES, MOVE_REVERSAL, MOVE_FLARE_BLITZ, MOVE_DOUBLEEDGE, MOVE_EXTRASENSORY, MOVE_FORESIGHT, MOVE_CRUSH_CLAW, MOVE_HOWL, MOVE_NATURE_POWER,
		/*009B »ðÇòÊó*/

		POKE_TOTODILE + 20000, MOVE_ICE_PUNCH, MOVE_FLATTER, MOVE_THRASH, MOVE_BLOCK, MOVE_FAKE_TEARS, MOVE_METAL_CLAW, MOVE_DRAGON_DANCE, MOVE_AQUA_JET, MOVE_HYDRO_PUMP, MOVE_WATER_PULSE, MOVE_MUD_SPORT, MOVE_WATER_SPORT, MOVE_CRUNCH, MOVE_ANCIENT_POWER,
		/*009E Ð¡¾âöù*/

		POKE_SENTRET + 20000, MOVE_ASSIST, MOVE_FOCUS_ENERGY, MOVE_COVET, MOVE_SLASH, MOVE_REVERSAL, MOVE_CHARM, MOVE_DOUBLEEDGE, MOVE_IRON_TAIL, MOVE_TRICK, MOVE_CAPTIVATE, MOVE_NUZZLE, MOVE_LAST_RESORT, MOVE_PURSUIT, MOVE_NATURAL_GIFT,
		/*00A1 Î²Á¢*/

		POKE_HOOTHOOT + 20000, MOVE_HURRICANE, MOVE_SUPERSONIC, MOVE_WING_ATTACK, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_AGILITY, MOVE_MEAN_LOOK, MOVE_NIGHT_SHADE, MOVE_DEFOG, MOVE_SKY_ATTACK, MOVE_MIRROR_MOVE, MOVE_FEATHER_DANCE,
		/*00A3 ¹¾¹¾*/

		POKE_LEDYBA + 20000, MOVE_BUG_BUZZ, MOVE_BUG_BITE, MOVE_SCREECH, MOVE_PSYBEAM, MOVE_DIZZY_PUNCH, MOVE_KNOCK_OFF, MOVE_BIDE, MOVE_COUNTER, MOVE_TAILWIND, MOVE_ENDURE, MOVE_DRAIN_PUNCH, MOVE_SILVER_WIND, MOVE_ENCORE, MOVE_FOCUS_PUNCH,
		/*00A5 °ÅÆ°³æ*/

		POKE_SPINARAK + 20000, MOVE_NIGHT_SLASH, MOVE_MEGAHORN, MOVE_ELECTROWEB, MOVE_DISABLE, MOVE_TOXIC_SPIKES, MOVE_RAGE_POWDER, MOVE_PSYBEAM, MOVE_BATON_PASS, MOVE_LUNGE, MOVE_TWINEEDLE, MOVE_SIGNAL_BEAM, MOVE_SONIC_BOOM, MOVE_PURSUIT,
		/*00A7 Ô²Ë¿Öë*/

		POKE_CHINCHOU + 20000, MOVE_MIST, MOVE_WHIRLPOOL, MOVE_SCREECH, MOVE_SHOCK_WAVE, MOVE_AGILITY, MOVE_PSYBEAM, MOVE_SOAK, MOVE_WATER_PULSE, MOVE_AMNESIA, MOVE_BRINE, MOVE_FLAIL,
		/*00AA µÆÁýÓã*/

		POKE_PICHU + 20000, MOVE_CHARGE, MOVE_BESTOW, MOVE_ELECTRIC_TERRAIN, MOVE_VOLT_TACKLE, MOVE_FAKE_OUT, MOVE_THUNDER_PUNCH, MOVE_PRESENT, MOVE_DOUBLE_SLAP, MOVE_DISARMING_VOICE, MOVE_TICKLE, MOVE_WISH, MOVE_REVERSAL, MOVE_ENDURE, MOVE_LUCKY_CHANT, MOVE_ENCORE, MOVE_FLAIL,
		/*00AC Æ¤Çð*/

		POKE_CLEFFA + 20000, MOVE_MISTY_TERRAIN, MOVE_AROMATHERAPY, MOVE_STORED_POWER, MOVE_BELLY_DRUM, MOVE_METRONOME, MOVE_FAKE_TEARS, MOVE_COVET, MOVE_PRESENT, MOVE_MIMIC, MOVE_TICKLE, MOVE_WISH, MOVE_AMNESIA, MOVE_SPLASH, MOVE_HEAL_PULSE,
		/*00AD Æ¤±¦±¦*/

		POKE_IGGLYBUFF + 20000, MOVE_MISTY_TERRAIN, MOVE_PUNISHMENT, MOVE_FEINT_ATTACK, MOVE_FAKE_TEARS, MOVE_COVET, MOVE_PRESENT, MOVE_SLEEP_TALK, MOVE_PERISH_SONG, MOVE_WISH, MOVE_CAPTIVATE, MOVE_LAST_RESORT, MOVE_HEAL_PULSE, MOVE_GRAVITY,
		/*00AE ±¦±¦¶¡*/

		POKE_TOGEPI + 20000, MOVE_MORNING_SUN, MOVE_STORED_POWER, MOVE_NASTY_PLOT, MOVE_PSYCHO_SHIFT, MOVE_PRESENT, MOVE_SECRET_POWER, MOVE_EXTRASENSORY, MOVE_FORESIGHT, MOVE_LUCKY_CHANT, MOVE_MIRROR_MOVE, MOVE_FUTURE_SIGHT, MOVE_PECK,
		/*00AF ²¨¿Ë±È*/

		POKE_NATU + 20000, MOVE_FEINT_ATTACK, MOVE_SIMPLE_BEAM, MOVE_QUICK_ATTACK, MOVE_STEEL_WING, MOVE_HAZE, MOVE_REFRESH, MOVE_ALLY_SWITCH, MOVE_SKILL_SWAP, MOVE_SYNCHRONOISE, MOVE_SUCKER_PUNCH, MOVE_ZEN_HEADBUTT, MOVE_FEATHER_DANCE, MOVE_ROOST, MOVE_DRILL_PECK,
		/*00B1 ÌìÈ»È¸*/

		POKE_MAREEP + 20000, MOVE_CHARGE, MOVE_FLATTER, MOVE_SCREECH, MOVE_ELECTRIC_TERRAIN, MOVE_AGILITY, MOVE_EERIE_IMPULSE, MOVE_TAKE_DOWN, MOVE_AFTER_YOU, MOVE_SAND_ATTACK, MOVE_ODOR_SLEUTH, MOVE_BODY_SLAM, MOVE_IRON_TAIL,
		/*00B3 ßãÀûÑò*/

		POKE_MARILL + 20000, MOVE_SING, MOVE_SUPERSONIC, MOVE_COPYCAT, MOVE_BELLY_DRUM, MOVE_REFRESH, MOVE_FAKE_TEARS, MOVE_SOAK, MOVE_SUPERPOWER, MOVE_PERISH_SONG, MOVE_TICKLE, MOVE_SLAM, MOVE_AQUA_JET, MOVE_AMNESIA, MOVE_BODY_SLAM, MOVE_ENCORE, MOVE_MUDDY_WATER,
		/*00B7 ÂêÁ¦Â¶*/

		POKE_SUDOWOODO + 20000, MOVE_HARDEN, MOVE_DEFENSE_CURL, MOVE_ROLLOUT, MOVE_SAND_TOMB, MOVE_ENDURE, MOVE_HEADBUTT, MOVE_STEALTH_ROCK, MOVE_SELFDESTRUCT, MOVE_CURSE,
		/*00B9 Ê÷²Å¹Ö*/

		POKE_HOPPIP + 20000, MOVE_HELPING_HAND, MOVE_WORRY_SEED, MOVE_AROMATHERAPY, MOVE_COTTON_GUARD, MOVE_CONFUSION, MOVE_GRASSY_TERRAIN, MOVE_DOUBLEEDGE, MOVE_AMNESIA, MOVE_ENDURE, MOVE_STRENGTH_SAP, MOVE_ENCORE, MOVE_SEED_BOMB,
		/*00BB ë¦×Ó²Ý*/

		POKE_AIPOM + 20000, MOVE_REVENGE, MOVE_SCREECH, MOVE_BOUNCE, MOVE_SWITCHEROO, MOVE_AGILITY, MOVE_FAKE_OUT, MOVE_COVET, MOVE_QUICK_GUARD, MOVE_DOUBLE_SLAP, MOVE_TAIL_SLAP, MOVE_SLAM, MOVE_COUNTER, MOVE_BEAT_UP, MOVE_SPITE, MOVE_PURSUIT,
		/*00BE ³¤Î²¹ÖÊÖ*/

		POKE_SUNKERN + 20000, MOVE_HELPING_HAND, MOVE_GRASS_WHISTLE, MOVE_MORNING_SUN, MOVE_LEECH_SEED, MOVE_GRASSY_TERRAIN, MOVE_BIDE, MOVE_SWEET_SCENT, MOVE_ENDURE, MOVE_ENCORE, MOVE_INGRAIN, MOVE_NATURAL_GIFT, MOVE_NATURE_POWER, MOVE_CURSE,
		/*00BF ÏòÈÕÖÖ×Ó*/

		POKE_YANMA + 20000, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_SECRET_POWER, MOVE_REVERSAL, MOVE_DOUBLEEDGE, MOVE_LEECH_LIFE, MOVE_SIGNAL_BEAM, MOVE_FEINT, MOVE_SILVER_WIND, MOVE_PURSUIT,
		/*00C1 òßòßòÑ*/

		POKE_WOOPER + 20000, MOVE_DOUBLE_KICK, MOVE_GUARD_SWAP, MOVE_EERIE_IMPULSE, MOVE_SLEEP_TALK, MOVE_AFTER_YOU, MOVE_SPIT_UP, MOVE_COUNTER, MOVE_ACID_SPRAY, MOVE_BODY_SLAM, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_ANCIENT_POWER, MOVE_ENCORE, MOVE_OBLIVION_WING, MOVE_RECOVER, MOVE_CURSE,
		/*00C2 ÎÚ²¨*/

		POKE_MURKROW + 20000, MOVE_PUNISHMENT, MOVE_WING_ATTACK, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_FLATTER, MOVE_SCREECH, MOVE_ASSURANCE, MOVE_PSYCHO_SHIFT, MOVE_PERISH_SONG, MOVE_CONFUSE_RAY, MOVE_SKY_ATTACK, MOVE_MIRROR_MOVE, MOVE_BRAVE_BIRD, MOVE_FEATHER_DANCE, MOVE_ROOST, MOVE_DRILL_PECK,
		/*00C6 ºÚ°µÑ»*/

		POKE_MISDREAVUS + 20000, MOVE_SCREECH, MOVE_IMPRISON, MOVE_NASTY_PLOT, MOVE_MEMENTO, MOVE_WONDER_ROOM, MOVE_OMINOUS_WIND, MOVE_ME_FIRST, MOVE_SKILL_SWAP, MOVE_DESTINY_BOND, MOVE_SUCKER_PUNCH, MOVE_SHADOW_SNEAK, MOVE_SPITE, MOVE_CURSE,
		/*00C8 ÃÎÑý*/

		POKE_GIRAFARIG + 20000, MOVE_DOUBLE_KICK, MOVE_MEAN_LOOK, MOVE_PSYCHIC_TERRAIN, MOVE_PSYCHIC_FANGS, MOVE_MIRROR_COAT, MOVE_TAKE_DOWN, MOVE_SECRET_POWER, MOVE_MAGIC_COAT, MOVE_WISH, MOVE_FORESIGHT, MOVE_AMNESIA, MOVE_SKILL_SWAP, MOVE_BEAT_UP, MOVE_RAZOR_WIND, MOVE_FUTURE_SIGHT,
		/*00CB ÷è÷ëÆæ*/

		POKE_PINECO + 20000, MOVE_REVENGE, MOVE_TOXIC_SPIKES, MOVE_PIN_MISSILE, MOVE_SWIFT, MOVE_POWER_TRICK, MOVE_SAND_TOMB, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_ENDURE, MOVE_STEALTH_ROCK, MOVE_FLAIL,
		/*00CC é»¹ûÇò*/

		POKE_DUNSPARCE + 20000, MOVE_SNORE, MOVE_AGILITY, MOVE_HEX, MOVE_ASTONISH, MOVE_SLEEP_TALK, MOVE_SECRET_POWER, MOVE_MAGIC_COAT, MOVE_BIDE, MOVE_HEADBUTT, MOVE_TRUMP_CARD, MOVE_BITE, MOVE_ANCIENT_POWER, MOVE_CURSE,
		/*00CE ÍÁÁúµÜµÜ*/

		POKE_GLIGAR + 20000, MOVE_NIGHT_SLASH, MOVE_WING_ATTACK, MOVE_POISON_TAIL, MOVE_AGILITY, MOVE_BATON_PASS, MOVE_METAL_CLAW, MOVE_POWER_TRICK, MOVE_SAND_TOMB, MOVE_ROCK_CLIMB, MOVE_DOUBLEEDGE, MOVE_CROSS_POISON, MOVE_COUNTER, MOVE_RAZOR_WIND, MOVE_FEINT,
		/*00CF ÌìÐ«*/

		POKE_SNUBBULL + 20000, MOVE_ICE_FANG, MOVE_FEINT_ATTACK, MOVE_SNORE, MOVE_METRONOME, MOVE_FIRE_FANG, MOVE_FAKE_TEARS, MOVE_CLOSE_COMBAT, MOVE_THUNDER_FANG, MOVE_PRESENT, MOVE_MIMIC, MOVE_SMELLING_SALTS, MOVE_DOUBLEEDGE, MOVE_CRUNCH, MOVE_FOCUS_PUNCH, MOVE_HEAL_BELL,
		/*00D1 ²¼Â³*/

		POKE_QWILFISH + 20000, MOVE_SUPERSONIC, MOVE_HAZE, MOVE_ASTONISH, MOVE_BUBBLE_BEAM, MOVE_AQUA_JET, MOVE_WATER_PULSE, MOVE_ACID_SPRAY, MOVE_SIGNAL_BEAM, MOVE_BRINE, MOVE_FLAIL,
		/*00D3 Ç§ÕëÓã*/

		POKE_SHUCKLE + 20000, MOVE_HELPING_HAND, MOVE_FINAL_GAMBIT, MOVE_ACUPRESSURE, MOVE_SAND_TOMB, MOVE_KNOCK_OFF, MOVE_ACID, MOVE_SWEET_SCENT, MOVE_ROCK_BLAST, MOVE_MUDSLAP,
		/*00D5 ºøºø*/

		POKE_HERACROSS + 20000, MOVE_REVENGE, MOVE_HARDEN, MOVE_MEGAHORN, MOVE_SEISMIC_TOSS, MOVE_BIDE, MOVE_DOUBLEEDGE, MOVE_ROCK_BLAST, MOVE_FOCUS_PUNCH, MOVE_FLAIL, MOVE_PURSUIT,
		/*00D6 ºÕÀ­¿ËÂÞË¹*/

		POKE_SNEASEL + 20000, MOVE_ICE_PUNCH, MOVE_ICE_SHARD, MOVE_ICICLE_CRASH, MOVE_PUNISHMENT, MOVE_THROAT_CHOP, MOVE_DOUBLE_HIT, MOVE_FAKE_OUT, MOVE_ASSIST, MOVE_FORESIGHT, MOVE_COUNTER, MOVE_CRUSH_CLAW, MOVE_AVALANCHE, MOVE_FEINT, MOVE_BITE, MOVE_SPITE, MOVE_PURSUIT,
		/*00D7 áðÀ­*/

		POKE_TEDDIURSA + 20000, MOVE_NIGHT_SLASH, MOVE_SEISMIC_TOSS, MOVE_BELLY_DRUM, MOVE_YAWN, MOVE_FAKE_TEARS, MOVE_METAL_CLAW, MOVE_CLOSE_COMBAT, MOVE_TAKE_DOWN, MOVE_SLEEP_TALK, MOVE_DOUBLEEDGE, MOVE_CROSS_CHOP, MOVE_COUNTER, MOVE_PLAY_ROUGH, MOVE_CRUNCH, MOVE_CHIP_AWAY,
		/*00D8 ÐÜ±¦±¦*/

		POKE_SLUGMA + 20000, MOVE_EARTH_POWER, MOVE_GUARD_SWAP, MOVE_ROLLOUT, MOVE_INFERNO, MOVE_MEMENTO, MOVE_SPIT_UP, MOVE_HEAT_WAVE, MOVE_ACID_ARMOR, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_SMOKESCREEN, MOVE_CURSE,
		/*00DA ÈÛÑÒ³æ*/

		POKE_SWINUB + 20000, MOVE_ICICLE_CRASH, MOVE_ICICLE_SPEAR, MOVE_FISSURE, MOVE_FREEZEDRY, MOVE_TAKE_DOWN, MOVE_MUD_SHOT, MOVE_DOUBLEEDGE, MOVE_BODY_SLAM, MOVE_AVALANCHE, MOVE_BITE, MOVE_STEALTH_ROCK, MOVE_ANCIENT_POWER, MOVE_CURSE,
		/*00DC Ð¡É½Öí*/

		POKE_CORSOLA + 20000, MOVE_MIST, MOVE_CAMOUFLAGE, MOVE_ICICLE_SPEAR, MOVE_SCREECH, MOVE_BARRIER, MOVE_CONFUSE_RAY, MOVE_BIDE, MOVE_HEAD_SMASH, MOVE_AQUA_RING, MOVE_LIQUIDATION, MOVE_WATER_PULSE, MOVE_AMNESIA, MOVE_INGRAIN, MOVE_NATURE_POWER, MOVE_CURSE,
		/*00DE Ì«ÑôÉºº÷*/

		POKE_REMORAID + 20000, MOVE_SUPERSONIC, MOVE_SCREECH, MOVE_SNORE, MOVE_SWIFT, MOVE_HAZE, MOVE_AURORA_BEAM, MOVE_MUD_SHOT, MOVE_WATER_SPOUT, MOVE_WATER_PULSE, MOVE_ACID_SPRAY, MOVE_ROCK_BLAST, MOVE_OCTAZOOKA, MOVE_ENTRAINMENT, MOVE_FLAIL,
		/*00DF ÌúÅÚÓã*/

		POKE_DELIBIRD + 20000, MOVE_ICE_PUNCH, MOVE_ICY_WIND, MOVE_ICE_SHARD, MOVE_ICE_BALL, MOVE_BESTOW, MOVE_QUICK_ATTACK, MOVE_RAPID_SPIN, MOVE_FAKE_OUT, MOVE_AURORA_BEAM, MOVE_FREEZEDRY, MOVE_SPIKES, MOVE_COUNTER, MOVE_DESTINY_BOND, MOVE_FUTURE_SIGHT, MOVE_SPLASH,
		/*00E1 ÐÅÊ¹Äñ*/

		POKE_MANTINE + 20000, MOVE_WIDE_GUARD, MOVE_HAZE, MOVE_MIRROR_COAT, MOVE_TWISTER, MOVE_SLAM, MOVE_HYDRO_PUMP, MOVE_TAILWIND, MOVE_AMNESIA, MOVE_MUD_SPORT, MOVE_WATER_SPORT, MOVE_SIGNAL_BEAM, MOVE_SPLASH,
		/*00E2 ¾Þ³á·ÉÓã*/

		POKE_SKARMORY + 20000, MOVE_WHIRLWIND, MOVE_ASSURANCE, MOVE_GUARD_SWAP, MOVE_SKY_ATTACK, MOVE_ENDURE, MOVE_STEALTH_ROCK, MOVE_BRAVE_BIRD, MOVE_PURSUIT, MOVE_DRILL_PECK, MOVE_CURSE,
		/*00E3 ¿ø¼×Äñ*/

		POKE_HOUNDOUR + 20000, MOVE_PUNISHMENT, MOVE_RAGE, MOVE_NASTY_PLOT, MOVE_FIRE_SPIN, MOVE_FIRE_FANG, MOVE_THUNDER_FANG, MOVE_REVERSAL, MOVE_COUNTER, MOVE_DESTINY_BOND, MOVE_SUCKER_PUNCH, MOVE_BEAT_UP, MOVE_FEINT, MOVE_SPITE, MOVE_PURSUIT,
		/*00E4 ´÷Â³±È*/

		POKE_PHANPY + 20000, MOVE_ICE_SHARD, MOVE_SNORE, MOVE_FISSURE, MOVE_FOCUS_ENERGY, MOVE_ENDEAVOR, MOVE_HIGH_HORSEPOWER, MOVE_COUNTER, MOVE_HEAD_SMASH, MOVE_BODY_SLAM, MOVE_PLAY_ROUGH, MOVE_ANCIENT_POWER, MOVE_MUDSLAP, MOVE_HEAVY_SLAM,
		/*00E7 Ð¡Ð¡Ïó*/

		POKE_STANTLER + 20000, MOVE_MEGAHORN, MOVE_THRASH, MOVE_DISABLE, MOVE_DOUBLE_KICK, MOVE_RAGE, MOVE_ME_FIRST, MOVE_EXTRASENSORY, MOVE_MUD_SPORT, MOVE_BITE, MOVE_ZEN_HEADBUTT, MOVE_SPITE,
		/*00EA ¾ª½ÇÂ¹*/

		POKE_TYROGUE + 20000, MOVE_HELPING_HAND, MOVE_HIGH_JUMP_KICK, MOVE_RAPID_SPIN, MOVE_COUNTER, MOVE_ENDURE, MOVE_MIND_READER, MOVE_FEINT, MOVE_MACH_PUNCH, MOVE_VACUUM_WAVE, MOVE_PURSUIT, MOVE_BULLET_PUNCH,
		/*00EC ÎÞÎ·Ð¡×Ó*/

		POKE_SMOOCHUM + 20000, MOVE_ICE_PUNCH, MOVE_NASTY_PLOT, MOVE_WAKEUP_SLAP, MOVE_FAKE_OUT, MOVE_MIRACLE_EYE, MOVE_WISH, MOVE_CAPTIVATE, MOVE_MEDITATE,
		/*00EE ÃÔ´½ÍÞ*/

		POKE_ELEKID + 20000, MOVE_DYNAMIC_PUNCH, MOVE_HAMMER_ARM, MOVE_ICE_PUNCH, MOVE_ROLLING_KICK, MOVE_FIRE_PUNCH, MOVE_KARATE_CHOP, MOVE_BARRIER, MOVE_CROSS_CHOP, MOVE_FEINT, MOVE_MEDITATE, MOVE_FOCUS_PUNCH,
		/*00EF µç»÷¹Ö*/

		POKE_MAGBY + 20000, MOVE_MEGA_PUNCH, MOVE_DYNAMIC_PUNCH, MOVE_SCREECH, MOVE_BELCH, MOVE_BELLY_DRUM, MOVE_FOCUS_ENERGY, MOVE_KARATE_CHOP, MOVE_THUNDER_PUNCH, MOVE_POWER_SWAP, MOVE_BARRIER, MOVE_FLARE_BLITZ, MOVE_CROSS_CHOP, MOVE_IRON_TAIL, MOVE_MACH_PUNCH,
		/*00F0 Ñ¼×ì±¦±¦*/

		POKE_MILTANK + 20000, MOVE_HEART_STAMP, MOVE_HELPING_HAND, MOVE_HAMMER_ARM, MOVE_PUNISHMENT, MOVE_BELCH, MOVE_SEISMIC_TOSS, MOVE_PRESENT, MOVE_SLEEP_TALK, MOVE_DIZZY_PUNCH, MOVE_REVERSAL, MOVE_DOUBLEEDGE, MOVE_ENDURE, MOVE_NATURAL_GIFT, MOVE_CURSE,
		/*00F1 ´óÄÌ¹Þ*/

		POKE_LARVITAR + 20000, MOVE_STOMP, MOVE_ASSURANCE, MOVE_FOCUS_ENERGY, MOVE_DRAGON_DANCE, MOVE_OUTRAGE, MOVE_IRON_DEFENSE, MOVE_IRON_HEAD, MOVE_IRON_TAIL, MOVE_STEALTH_ROCK, MOVE_ANCIENT_POWER, MOVE_PURSUIT, MOVE_CURSE,
		/*00F6 Ó×»ùÀ­Ë¹*/

		POKE_TREECKO + 20000, MOVE_GRASS_WHISTLE, MOVE_DOUBLE_KICK, MOVE_WORRY_SEED, MOVE_LEAF_STORM, MOVE_SYNTHESIS, MOVE_LEECH_SEED, MOVE_DRAGON_BREATH, MOVE_ENDEAVOR, MOVE_MAGICAL_LEAF, MOVE_GRASSY_TERRAIN, MOVE_CRUSH_CLAW, MOVE_MUD_SPORT, MOVE_RAZOR_WIND, MOVE_CRUNCH, MOVE_BULLET_SEED, MOVE_NATURAL_GIFT,
		/*0115 Ä¾ÊØ¹¬*/

		POKE_TORCHIC + 20000, MOVE_NIGHT_SLASH, MOVE_AGILITY, MOVE_BATON_PASS, MOVE_FLAME_BURST, MOVE_REVERSAL, MOVE_SMELLING_SALTS, MOVE_COUNTER, MOVE_CRUSH_CLAW, MOVE_LOW_KICK, MOVE_ENDURE, MOVE_FEINT, MOVE_FEATHER_DANCE, MOVE_LAST_RESORT, MOVE_CURSE,
		/*0118 »ðÖÉ¼¦*/

		POKE_MUDKIP + 20000, MOVE_ICE_BALL, MOVE_STOMP, MOVE_WHIRLPOOL, MOVE_UPROAR, MOVE_WIDE_GUARD, MOVE_YAWN, MOVE_MIRROR_COAT, MOVE_MUD_BOMB, MOVE_BARRIER, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_SLUDGE, MOVE_AVALANCHE, MOVE_BITE, MOVE_ANCIENT_POWER, MOVE_CURSE,
		/*011B Ë®Ô¾Óã*/

		POKE_POOCHYENA + 20000, MOVE_ICE_FANG, MOVE_LEER, MOVE_YAWN, MOVE_FIRE_FANG, MOVE_ASTONISH, MOVE_POISON_FANG, MOVE_COVET, MOVE_THUNDER_FANG, MOVE_SLEEP_TALK, MOVE_SNATCH, MOVE_ME_FIRST, MOVE_SUCKER_PUNCH, MOVE_PLAY_ROUGH,
		/*011E ÍÁÀÇÈ®*/

		POKE_ZIGZAGOON + 20000, MOVE_HELPING_HAND, MOVE_SIMPLE_BEAM, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_ROCK_CLIMB, MOVE_CHARM, MOVE_EXTREME_SPEED, MOVE_TRICK, MOVE_MUDSLAP, MOVE_PURSUIT,
		/*0120 ÉßÎÆÐÜ*/

		POKE_LOTAD + 20000, MOVE_RAZOR_LEAF, MOVE_SYNTHESIS, MOVE_LEECH_SEED, MOVE_TICKLE, MOVE_COUNTER, MOVE_WATER_GUN, MOVE_SWEET_SCENT, MOVE_TEETER_DANCE, MOVE_GIGA_DRAIN, MOVE_FLAIL,
		/*0127 Á«Ò¶Í¯×Ó*/

		POKE_SEEDOT + 20000, MOVE_QUICK_ATTACK, MOVE_WORRY_SEED, MOVE_NASTY_PLOT, MOVE_LEECH_SEED, MOVE_POWER_SWAP, MOVE_TAKE_DOWN, MOVE_FOUL_PLAY, MOVE_GRASSY_TERRAIN, MOVE_DEFOG, MOVE_AMNESIA, MOVE_BEAT_UP, MOVE_RAZOR_WIND, MOVE_BULLET_SEED,
		/*012A ÏðÊµ¹û*/

		POKE_NINCADA + 20000, MOVE_NIGHT_SLASH, MOVE_FINAL_GAMBIT, MOVE_BUG_BUZZ, MOVE_BUG_BITE, MOVE_FEINT_ATTACK, MOVE_GUST, MOVE_ENDURE, MOVE_SILVER_WIND,
		/*012D ÍÁ¾ÓÈÌÊ¿*/

		POKE_TAILLOW + 20000, MOVE_HURRICANE, MOVE_BOOMBURST, MOVE_SUPERSONIC, MOVE_WHIRLWIND, MOVE_RAGE, MOVE_STEEL_WING, MOVE_REFRESH, MOVE_DEFOG, MOVE_SKY_ATTACK, MOVE_MIRROR_MOVE, MOVE_BRAVE_BIRD, MOVE_ROOST, MOVE_PURSUIT,
		/*0130 °Á¹ÇÑà*/

		POKE_SHROOMISH + 20000, MOVE_HELPING_HAND, MOVE_WORRY_SEED, MOVE_WAKEUP_SLAP, MOVE_FAKE_TEARS, MOVE_CHARM, MOVE_DRAIN_PUNCH, MOVE_FOCUS_PUNCH, MOVE_BULLET_SEED, MOVE_SEED_BOMB, MOVE_NATURAL_GIFT,
		/*0132 Ä¢Ä¢¹½*/

		POKE_SPINDA + 20000, MOVE_ROLE_PLAY, MOVE_ICY_WIND, MOVE_DISABLE, MOVE_GUARD_SPLIT, MOVE_RAPID_SPIN, MOVE_FAKE_OUT, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_PSYCHO_CUT, MOVE_PSYCHO_SHIFT, MOVE_SPOTLIGHT, MOVE_WISH, MOVE_SMELLING_SALTS, MOVE_WATER_PULSE, MOVE_TRICK, MOVE_ENCORE,
		/*0134 »Î»Î°ß*/

		POKE_WINGULL + 20000, MOVE_MIST, MOVE_AGILITY, MOVE_WIDE_GUARD, MOVE_SOAK, MOVE_TWISTER, MOVE_KNOCK_OFF, MOVE_GUST, MOVE_AQUA_RING, MOVE_WATER_SPORT, MOVE_BRINE, MOVE_ROOST,
		/*0135 ³¤³áÅ¸*/

		POKE_SURSKIT + 20000, MOVE_BUG_BITE, MOVE_PSYBEAM, MOVE_POWER_SPLIT, MOVE_LUNGE, MOVE_MUD_SHOT, MOVE_FORESIGHT, MOVE_AQUA_JET, MOVE_HYDRO_PUMP, MOVE_ENDURE, MOVE_MIND_READER, MOVE_SIGNAL_BEAM, MOVE_FELL_STINGER,
		/*0137 ÁïÁïÌÇÇò*/

		POKE_WAILMER + 20000, MOVE_DEFENSE_CURL, MOVE_SNORE, MOVE_THRASH, MOVE_FISSURE, MOVE_SOAK, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_CLEAR_SMOG, MOVE_DOUBLEEDGE, MOVE_AQUA_RING, MOVE_BODY_SLAM, MOVE_ZEN_HEADBUTT, MOVE_CURSE,
		/*0139 ºðºð¾¨*/

		POKE_SKITTY + 20000, MOVE_HELPING_HAND, MOVE_UPROAR, MOVE_SIMPLE_BEAM, MOVE_FAKE_OUT, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_TICKLE, MOVE_MUD_BOMB, MOVE_WISH, MOVE_SUCKER_PUNCH, MOVE_ZEN_HEADBUTT, MOVE_CAPTIVATE, MOVE_COSMIC_POWER, MOVE_LAST_RESORT,
		/*013B ÏòÎ²ß÷*/

		POKE_KECLEON + 20000, MOVE_CAMOUFLAGE, MOVE_DISABLE, MOVE_NASTY_PLOT, MOVE_FAKE_OUT, MOVE_DIZZY_PUNCH, MOVE_MAGIC_COAT, MOVE_FOUL_PLAY, MOVE_SNATCH, MOVE_SKILL_SWAP, MOVE_TRICK, MOVE_OBLIVION_WING, MOVE_RECOVER,
		/*013D ±äÒþÁú*/

		POKE_NOSEPASS + 20000, MOVE_BLOCK, MOVE_WIDE_GUARD, MOVE_ROLLOUT, MOVE_DOUBLEEDGE, MOVE_ENDURE, MOVE_STEALTH_ROCK, MOVE_MAGNITUDE,
		/*0140 ³¯±±±Ç*/

		POKE_TORKOAL + 20000, MOVE_FISSURE, MOVE_YAWN, MOVE_SKULL_BASH, MOVE_FLAME_BURST, MOVE_SUPERPOWER, MOVE_SLEEP_TALK, MOVE_ERUPTION, MOVE_CLEAR_SMOG, MOVE_ENDURE,
		/*0141 ÃºÌ¿¹ê*/

		POKE_SABLEYE + 20000, MOVE_FLATTER, MOVE_IMPRISON, MOVE_NASTY_PLOT, MOVE_MEAN_LOOK, MOVE_METAL_BURST, MOVE_SUCKER_PUNCH, MOVE_TRICK, MOVE_FEINT, MOVE_CAPTIVATE, MOVE_MOONLIGHT, MOVE_RECOVER,
		/*0142 ¹´»êÑÛ*/

		POKE_BARBOACH + 20000, MOVE_WHIRLPOOL, MOVE_EARTH_POWER, MOVE_THRASH, MOVE_SPARK, MOVE_DRAGON_DANCE, MOVE_TAKE_DOWN, MOVE_MUD_SHOT, MOVE_HYDRO_PUMP, MOVE_FLAIL, MOVE_MUDDY_WATER,
		/*0143 ÄàÄàöú*/

		POKE_LUVDISC + 20000, MOVE_SUPERSONIC, MOVE_AQUA_RING, MOVE_AQUA_JET, MOVE_MUD_SPORT, MOVE_WATER_SPORT, MOVE_BRINE, MOVE_CAPTIVATE, MOVE_SPLASH, MOVE_ENTRAINMENT, MOVE_HEAL_PULSE,
		/*0145 °®ÐÄÓã*/

		POKE_CORPHISH + 20000, MOVE_SWITCHEROO, MOVE_METAL_CLAW, MOVE_DRAGON_DANCE, MOVE_ENDEAVOR, MOVE_SUPERPOWER, MOVE_KNOCK_OFF, MOVE_DOUBLEEDGE, MOVE_AQUA_JET, MOVE_BODY_SLAM, MOVE_MUD_SPORT, MOVE_TRUMP_CARD, MOVE_ANCIENT_POWER, MOVE_CHIP_AWAY,
		/*0146 ÁúÏºÐ¡±ø*/

		POKE_FEEBAS + 20000, MOVE_MIST, MOVE_HYPNOSIS, MOVE_HAZE, MOVE_MIRROR_COAT, MOVE_DRAGON_BREATH, MOVE_DRAGON_PULSE, MOVE_TICKLE, MOVE_CONFUSE_RAY, MOVE_IRON_TAIL, MOVE_MUD_SPORT, MOVE_BRINE, MOVE_CAPTIVATE,
		/*0148 ³ó³óÓã*/

		POKE_CARVANHA + 20000, MOVE_THRASH, MOVE_SWIFT, MOVE_PSYCHIC_FANGS, MOVE_DOUBLEEDGE, MOVE_HYDRO_PUMP, MOVE_DESTINY_BOND, MOVE_BRINE, MOVE_ANCIENT_POWER,
		/*014A ÀûÑÀÓã*/

		POKE_TRAPINCH + 20000, MOVE_BUG_BITE, MOVE_EARTH_POWER, MOVE_QUICK_ATTACK, MOVE_FOCUS_ENERGY, MOVE_FURY_CUTTER, MOVE_MUD_SHOT, MOVE_GUST, MOVE_ENDURE, MOVE_SIGNAL_BEAM, MOVE_FLAIL,
		/*014C ´óò¦ÒÏ*/

		POKE_MAKUHITA + 20000, MOVE_HELPING_HAND, MOVE_REVENGE, MOVE_DYNAMIC_PUNCH, MOVE_FEINT_ATTACK, MOVE_WIDE_GUARD, MOVE_WAKEUP_SLAP, MOVE_DETECT, MOVE_CROSS_CHOP, MOVE_FORESIGHT, MOVE_COUNTER, MOVE_FEINT, MOVE_FOCUS_PUNCH, MOVE_CHIP_AWAY, MOVE_BULLET_PUNCH,
		/*014F Ä»ÏÂÁ¦Ê¿*/

		POKE_ELECTRIKE + 20000, MOVE_ICE_FANG, MOVE_UPROAR, MOVE_SHOCK_WAVE, MOVE_ELECTRO_BALL, MOVE_SWITCHEROO, MOVE_DISCHARGE, MOVE_SWIFT, MOVE_EERIE_IMPULSE, MOVE_FIRE_FANG, MOVE_THUNDER_FANG, MOVE_FLAME_BURST, MOVE_HEADBUTT, MOVE_CRUNCH, MOVE_CURSE,
		/*0151 ÂäÀ×ÊÞ*/

		POKE_NUMEL + 20000, MOVE_DEFENSE_CURL, MOVE_STOMP, MOVE_SCARY_FACE, MOVE_ROLLOUT, MOVE_MUD_BOMB, MOVE_SPIT_UP, MOVE_HEAT_WAVE, MOVE_GROWTH, MOVE_BODY_SLAM, MOVE_IRON_HEAD, MOVE_ENDURE, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_ANCIENT_POWER, MOVE_HOWL, MOVE_HEAVY_SLAM,
		/*0153 ´ô»ðÍÕ*/

		POKE_SPHEAL + 20000, MOVE_FISSURE, MOVE_BELLY_DRUM, MOVE_ROLLOUT, MOVE_YAWN, MOVE_SLEEP_TALK, MOVE_SPIT_UP, MOVE_AQUA_RING, MOVE_WATER_PULSE, MOVE_SWALLOW, MOVE_WATER_SPORT, MOVE_SIGNAL_BEAM, MOVE_STOCKPILE, MOVE_CURSE,
		/*0155 º£±ªÇò*/

		POKE_CACNEA + 20000, MOVE_DYNAMIC_PUNCH, MOVE_GRASS_WHISTLE, MOVE_BELCH, MOVE_BLOCK, MOVE_SWITCHEROO, MOVE_DISABLE, MOVE_ROTOTILLER, MOVE_NASTY_PLOT, MOVE_MAGICAL_LEAF, MOVE_SMELLING_SALTS, MOVE_ACID, MOVE_COUNTER, MOVE_LOW_KICK, MOVE_TEETER_DANCE, MOVE_OBLIVION_WING, MOVE_FELL_STINGER,
		/*0158 ´ÌÇòÏÉÈËÕÆ*/

		POKE_SNORUNT + 20000, MOVE_BLOCK, MOVE_SWITCHEROO, MOVE_DISABLE, MOVE_ROLLOUT, MOVE_HEX, MOVE_FAKE_TEARS, MOVE_WEATHER_BALL, MOVE_BIDE, MOVE_SPIKES, MOVE_AVALANCHE,
		/*015A Ñ©Í¯×Ó*/

		POKE_AZURILL + 20000, MOVE_CAMOUFLAGE, MOVE_SING, MOVE_COPYCAT, MOVE_REFRESH, MOVE_FAKE_TEARS, MOVE_SOAK, MOVE_TICKLE, MOVE_SLAM, MOVE_BODY_SLAM, MOVE_WATER_SPORT, MOVE_ENCORE, MOVE_MUDDY_WATER,
		/*015E Â¶Á¦Àö*/

		POKE_SPOINK + 20000, MOVE_WHIRLWIND, MOVE_SIMPLE_BEAM, MOVE_MIRROR_COAT, MOVE_EXTRASENSORY, MOVE_AMNESIA, MOVE_SKILL_SWAP, MOVE_ENDURE, MOVE_TRICK, MOVE_LUCKY_CHANT, MOVE_ZEN_HEADBUTT, MOVE_FUTURE_SIGHT,
		/*015F ÌøÌøÖí*/

		POKE_PLUSLE + 20000, MOVE_SING, MOVE_DISCHARGE, MOVE_FAKE_TEARS, MOVE_TEARFUL_LOOK, MOVE_WISH, MOVE_CHARM, MOVE_SWEET_KISS, MOVE_LUCKY_CHANT,
		/*0161 ÕýµçÅÄÅÄ*/

		POKE_MINUM + 20000, MOVE_SING, MOVE_DISCHARGE, MOVE_FAKE_TEARS, MOVE_TEARFUL_LOOK, MOVE_WISH, MOVE_CHARM, MOVE_SWEET_KISS, MOVE_LUCKY_CHANT,
		/*0162 ¸ºµçÅÄÅÄ*/

		POKE_MAWILE + 20000, MOVE_MISTY_TERRAIN, MOVE_ICE_FANG, MOVE_PUNISHMENT, MOVE_SEISMIC_TOSS, MOVE_GUARD_SWAP, MOVE_FIRE_FANG, MOVE_METAL_BURST, MOVE_POISON_FANG, MOVE_THUNDER_FANG, MOVE_TICKLE, MOVE_SLAM, MOVE_SUCKER_PUNCH, MOVE_CAPTIVATE, MOVE_ANCIENT_POWER, MOVE_OBLIVION_WING,
		/*0163 ´ó×ìÍÞ*/

		POKE_MEDITITE + 20000, MOVE_DYNAMIC_PUNCH, MOVE_ICE_PUNCH, MOVE_GUARD_SWAP, MOVE_FIRE_PUNCH, MOVE_FAKE_OUT, MOVE_BATON_PASS, MOVE_PSYCHO_CUT, MOVE_QUICK_GUARD, MOVE_THUNDER_PUNCH, MOVE_POWER_SWAP, MOVE_SECRET_POWER, MOVE_FORESIGHT, MOVE_DRAIN_PUNCH, MOVE_BULLET_PUNCH,
		/*0164 ÂêÉ³ÄÇ*/

		POKE_SWABLU + 20000, MOVE_RAGE, MOVE_STEEL_WING, MOVE_AGILITY, MOVE_HAZE, MOVE_HYPER_VOICE, MOVE_POWER_SWAP, MOVE_DRAGON_RUSH, MOVE_PLAY_ROUGH, MOVE_FEATHER_DANCE, MOVE_ROOST, MOVE_PURSUIT,
		/*0166 ÇàÃàÄñ*/

		POKE_DUSKULL + 20000, MOVE_FEINT_ATTACK, MOVE_DARK_PULSE, MOVE_PAIN_SPLIT, MOVE_IMPRISON, MOVE_HAZE, MOVE_MEMENTO, MOVE_OMINOUS_WIND, MOVE_SKILL_SWAP, MOVE_DESTINY_BOND, MOVE_GRUDGE,
		/*0169 Ò¹Ñ²Áé*/

		POKE_ROSELIA + 20000, MOVE_GRASS_WHISTLE, MOVE_SLEEP_POWDER, MOVE_PIN_MISSILE, MOVE_LEAF_STORM, MOVE_RAZOR_LEAF, MOVE_SYNTHESIS, MOVE_COTTON_SPORE, MOVE_POWER_WHIP, MOVE_SPIKES, MOVE_EXTRASENSORY, MOVE_MIND_READER, MOVE_GIGA_DRAIN, MOVE_BULLET_SEED, MOVE_SEED_BOMB, MOVE_NATURAL_GIFT,
		/*016B ¶¾Ç¾Þ±*/

		POKE_SLAKOTH + 20000, MOVE_NIGHT_SLASH, MOVE_HAMMER_ARM, MOVE_SNORE, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_AFTER_YOU, MOVE_SLASH, MOVE_CRUSH_CLAW, MOVE_BODY_SLAM, MOVE_PURSUIT, MOVE_CURSE,
		/*016C ÀÁÈËÌ¡*/

		POKE_GULPIN + 20000, MOVE_VENOM_DRENCH, MOVE_PAIN_SPLIT, MOVE_GUNK_SHOT, MOVE_ACID_ARMOR, MOVE_DESTINY_BOND, MOVE_MUDSLAP, MOVE_SMOG, MOVE_CURSE,
		/*016F ÈÜÊ³ÊÞ*/

		POKE_TROPIUS + 20000, MOVE_LEAF_STORM, MOVE_SYNTHESIS, MOVE_LEECH_SEED, MOVE_DRAGON_HAMMER, MOVE_DRAGON_DANCE, MOVE_SLAM, MOVE_HEADBUTT, MOVE_RAZOR_WIND, MOVE_LEAF_BLADE, MOVE_BULLET_SEED, MOVE_NATURAL_GIFT, MOVE_NATURE_POWER, MOVE_CURSE,
		/*0171 ÈÈ´øÁú*/

		POKE_WHISMUR + 20000, MOVE_CIRCLE_THROW, MOVE_HAMMER_ARM, MOVE_WHIRLWIND, MOVE_SNORE, MOVE_FAKE_TEARS, MOVE_ENDEAVOR, MOVE_DISARMING_VOICE, MOVE_TAKE_DOWN, MOVE_SMELLING_SALTS, MOVE_EXTRASENSORY, MOVE_SMOKESCREEN,
		/*0172 ¹¾æ¤æ¤*/

		POKE_CLAMPERL + 20000, MOVE_SUPERSONIC, MOVE_REFRESH, MOVE_BARRIER, MOVE_CONFUSE_RAY, MOVE_AQUA_RING, MOVE_WATER_PULSE, MOVE_BODY_SLAM, MOVE_ENDURE, MOVE_MUD_SPORT, MOVE_BRINE, MOVE_MUDDY_WATER,
		/*0175 ÕäÖé±´*/

		POKE_ABSOL + 20000, MOVE_MEGAHORN, MOVE_PUNISHMENT, MOVE_FEINT_ATTACK, MOVE_ASSURANCE, MOVE_MEAN_LOOK, MOVE_HEX, MOVE_BATON_PASS, MOVE_PERISH_SONG, MOVE_MAGIC_COAT, MOVE_ME_FIRST, MOVE_DOUBLEEDGE, MOVE_SUCKER_PUNCH, MOVE_PLAY_ROUGH, MOVE_ZEN_HEADBUTT, MOVE_CURSE,
		/*0178 °¢²ªËóÂ³*/

		POKE_SHUPPET + 20000, MOVE_DISABLE, MOVE_IMPRISON, MOVE_ASTONISH, MOVE_GUNK_SHOT, MOVE_OMINOUS_WIND, MOVE_CONFUSE_RAY, MOVE_PHANTOM_FORCE, MOVE_FORESIGHT, MOVE_DESTINY_BOND, MOVE_SHADOW_SNEAK, MOVE_PURSUIT,
		/*0179 Ô¹Ó°ÍÞÍÞ*/

		POKE_SEVIPER + 20000, MOVE_NIGHT_SLASH, MOVE_FINAL_GAMBIT, MOVE_PUNISHMENT, MOVE_SWITCHEROO, MOVE_ASSURANCE, MOVE_SCARY_FACE, MOVE_WRING_OUT, MOVE_SPIT_UP, MOVE_BODY_SLAM, MOVE_IRON_TAIL, MOVE_SWALLOW, MOVE_STOCKPILE,
		/*017B ·¹³×Éß*/

		POKE_ZANGOOSE + 20000, MOVE_NIGHT_SLASH, MOVE_FINAL_GAMBIT, MOVE_DISABLE, MOVE_DOUBLE_HIT, MOVE_DOUBLE_KICK, MOVE_BELLY_DRUM, MOVE_METAL_CLAW, MOVE_QUICK_GUARD, MOVE_FURY_SWIPES, MOVE_COUNTER, MOVE_IRON_TAIL, MOVE_RAZOR_WIND, MOVE_FEINT, MOVE_FLAIL, MOVE_CURSE,
		/*017C Ã¨÷øÕ¶*/

		POKE_RELICANTH + 20000, MOVE_SNORE, MOVE_SKULL_BASH, MOVE_SLEEP_TALK, MOVE_MUD_SHOT, MOVE_AQUA_TAIL, MOVE_AMNESIA, MOVE_WATER_SPORT, MOVE_BRINE, MOVE_ZEN_HEADBUTT, MOVE_MAGNITUDE, MOVE_MUDSLAP, MOVE_MUDDY_WATER,
		/*017D ¹Å¿Õ¼¬Óã*/

		POKE_ARON + 20000, MOVE_STOMP, MOVE_SCREECH, MOVE_DRAGON_RUSH, MOVE_ENDEAVOR, MOVE_SUPERPOWER, MOVE_REVERSAL, MOVE_SMELLING_SALTS, MOVE_HEAD_SMASH, MOVE_BODY_SLAM, MOVE_IRON_HEAD, MOVE_STEALTH_ROCK, MOVE_CURSE,
		/*017E ¿É¿É¶àÀ­*/

		POKE_CASTFORM + 20000, MOVE_DISABLE, MOVE_GUARD_SWAP, MOVE_HEX, MOVE_REFLECT_TYPE, MOVE_OMINOUS_WIND, MOVE_CLEAR_SMOG, MOVE_AMNESIA, MOVE_LUCKY_CHANT, MOVE_COSMIC_POWER, MOVE_FUTURE_SIGHT,
		/*0181 Æ®¸¡ÅÝÅÝ*/

		POKE_VOLBEAT + 20000, MOVE_BUG_BUZZ, MOVE_SEISMIC_TOSS, MOVE_BATON_PASS, MOVE_LUNGE, MOVE_DIZZY_PUNCH, MOVE_TRICK, MOVE_SILVER_WIND, MOVE_ENCORE,
		/*0182 µçÓ©³æ*/

		POKE_ILLUMISE + 20000, MOVE_BUG_BUZZ, MOVE_AROMATHERAPY, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_CONFUSE_RAY, MOVE_GROWTH, MOVE_SILVER_WIND, MOVE_CAPTIVATE, MOVE_ENCORE,
		/*0183 ÌðÌðÓ©*/

		POKE_LILEEP + 20000, MOVE_MEGA_DRAIN, MOVE_WRING_OUT, MOVE_MIRROR_COAT, MOVE_TICKLE, MOVE_BARRIER, MOVE_ENDURE, MOVE_STEALTH_ROCK, MOVE_RECOVER, MOVE_CURSE,
		/*0184 ´¥ÊÖ°ÙºÏ*/

		POKE_ANORITH + 20000, MOVE_SCREECH, MOVE_RAPID_SPIN, MOVE_KNOCK_OFF, MOVE_SAND_ATTACK, MOVE_CROSS_POISON, MOVE_AQUA_JET, MOVE_WATER_PULSE, MOVE_IRON_DEFENSE, MOVE_CURSE,
		/*0186 Ì«¹ÅÓð³æ*/

		POKE_RALTS + 20000, MOVE_MISTY_TERRAIN, MOVE_DISABLE, MOVE_MEAN_LOOK, MOVE_ALLY_SWITCH, MOVE_MEMENTO, MOVE_CONFUSE_RAY, MOVE_SKILL_SWAP, MOVE_SYNCHRONOISE, MOVE_DESTINY_BOND, MOVE_SHADOW_SNEAK, MOVE_GRUDGE, MOVE_ENCORE,
		/*0188 À­Â³À­Ë¿*/

		POKE_BAGON + 20000, MOVE_DEFENSE_CURL, MOVE_THRASH, MOVE_FIRE_FANG, MOVE_TWISTER, MOVE_DRAGON_PULSE, MOVE_DRAGON_RUSH, MOVE_DRAGON_RAGE, MOVE_DRAGON_DANCE, MOVE_HYDRO_PUMP, MOVE_ENDURE,
		/*018B ±¦±´Áú*/

		POKE_CHIMECHO + 20000, MOVE_HYPNOSIS, MOVE_DISABLE, MOVE_STORED_POWER, MOVE_PERISH_SONG, MOVE_WISH, MOVE_SKILL_SWAP, MOVE_CRAFTY_SHIELD, MOVE_COSMIC_POWER, MOVE_FUTURE_SIGHT, MOVE_RECOVER, MOVE_CURSE,
		/*019B ·çÁåÁå*/

		POKE_TURTWIG + 20000, MOVE_EARTH_POWER, MOVE_THRASH, MOVE_WORRY_SEED, MOVE_WIDE_GUARD, MOVE_SAND_TOMB, MOVE_SUPERPOWER, MOVE_TICKLE, MOVE_SPIT_UP, MOVE_GRASSY_TERRAIN, MOVE_DOUBLEEDGE, MOVE_GROWTH, MOVE_AMNESIA, MOVE_BODY_SLAM, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_HEAVY_SLAM,
		/*01B8 ²ÝÃç¹ê*/

		POKE_CHIMCHAR + 20000, MOVE_HELPING_HAND, MOVE_SUBMISSION, MOVE_DOUBLE_KICK, MOVE_FIRE_PUNCH, MOVE_BLAZE_KICK, MOVE_FAKE_OUT, MOVE_ASSIST, MOVE_FOCUS_ENERGY, MOVE_QUICK_GUARD, MOVE_THUNDER_PUNCH, MOVE_HEAT_WAVE, MOVE_COUNTER, MOVE_ENCORE, MOVE_OBLIVION_WING, MOVE_FOCUS_PUNCH,
		/*01BB Ð¡»ðÑæºï*/

		POKE_PIPLUP + 20000, MOVE_ICY_WIND, MOVE_SUPERSONIC, MOVE_SNORE, MOVE_DOUBLE_HIT, MOVE_AGILITY, MOVE_YAWN, MOVE_BIDE, MOVE_AQUA_RING, MOVE_HYDRO_PUMP, MOVE_MUD_SPORT, MOVE_POWER_TRIP, MOVE_FEATHER_DANCE, MOVE_MUDSLAP, MOVE_FLAIL,
		/*01BE ²¨¼ÓÂü*/

		POKE_STARLY + 20000, MOVE_REVENGE, MOVE_UPROAR, MOVE_STEEL_WING, MOVE_ASTONISH, MOVE_DETECT, MOVE_FURY_ATTACK, MOVE_SAND_ATTACK, MOVE_DOUBLEEDGE, MOVE_FORESIGHT, MOVE_MIRROR_MOVE, MOVE_FEATHER_DANCE, MOVE_ROOST, MOVE_PURSUIT,
		/*01C1 Ä·¿Ë¶ù*/

		POKE_BIDOOF + 20000, MOVE_DEFENSE_CURL, MOVE_QUICK_ATTACK, MOVE_ROLLOUT, MOVE_SKULL_BASH, MOVE_FURY_SWIPES, MOVE_SLEEP_TALK, MOVE_ROCK_CLIMB, MOVE_ODOR_SLEUTH, MOVE_DOUBLEEDGE, MOVE_AQUA_TAIL, MOVE_ENDURE, MOVE_MUD_SPORT, MOVE_WATER_SPORT,
		/*01C4 ´óÑÀÀê*/

		POKE_SHINX + 20000, MOVE_NIGHT_SLASH, MOVE_HELPING_HAND, MOVE_ICE_FANG, MOVE_QUICK_ATTACK, MOVE_SHOCK_WAVE, MOVE_DOUBLE_KICK, MOVE_SWIFT, MOVE_EERIE_IMPULSE, MOVE_FIRE_FANG, MOVE_FAKE_TEARS, MOVE_THUNDER_FANG, MOVE_TAKE_DOWN, MOVE_SIGNAL_BEAM, MOVE_HOWL,
		/*01C8 Ð¡Ã¨¹Ö*/

		POKE_BUDEW + 20000, MOVE_GRASS_WHISTLE, MOVE_SLEEP_POWDER, MOVE_PIN_MISSILE, MOVE_LEAF_STORM, MOVE_RAZOR_LEAF, MOVE_SYNTHESIS, MOVE_COTTON_SPORE, MOVE_SPIKES, MOVE_EXTRASENSORY, MOVE_MIND_READER, MOVE_GIGA_DRAIN, MOVE_SEED_BOMB, MOVE_NATURAL_GIFT,
		/*01CB º¬Ðß°ú*/

		POKE_CRANIDOS + 20000, MOVE_HAMMER_ARM, MOVE_STOMP, MOVE_WHIRLWIND, MOVE_THRASH, MOVE_LEER, MOVE_DOUBLEEDGE, MOVE_SLAM, MOVE_IRON_HEAD, MOVE_IRON_TAIL, MOVE_CRUNCH, MOVE_CURSE,
		/*01CD Í·¸ÇÁú*/

		POKE_SHIELDON + 20000, MOVE_SCREECH, MOVE_FISSURE, MOVE_GUARD_SPLIT, MOVE_WIDE_GUARD, MOVE_SCARY_FACE, MOVE_FOCUS_ENERGY, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_BODY_SLAM, MOVE_HEADBUTT, MOVE_ROCK_BLAST, MOVE_STEALTH_ROCK, MOVE_CURSE,
		/*01CF ¶Ü¼×Áú*/

		POKE_PACHIRISU + 20000, MOVE_DEFENSE_CURL, MOVE_CHARGE, MOVE_BESTOW, MOVE_FLATTER, MOVE_ION_DELUGE, MOVE_ROLLOUT, MOVE_FAKE_TEARS, MOVE_FOLLOW_ME, MOVE_COVET, MOVE_IRON_TAIL, MOVE_TAIL_WHIP, MOVE_BITE, MOVE_NUZZLE, MOVE_FLAIL,
		/*01D6 ÅÁÆæÀû×È*/

		POKE_BUIZEL + 20000, MOVE_HELPING_HAND, MOVE_SWITCHEROO, MOVE_BATON_PASS, MOVE_SOAK, MOVE_DOUBLE_SLAP, MOVE_FURY_CUTTER, MOVE_FURY_SWIPES, MOVE_SLASH, MOVE_ODOR_SLEUTH, MOVE_ME_FIRST, MOVE_TAIL_SLAP, MOVE_AQUA_RING, MOVE_AQUA_TAIL, MOVE_HEADBUTT, MOVE_MUDSLAP,
		/*01D7 Ó¾È¦÷ø*/

		POKE_CHERUBI + 20000, MOVE_DEFENSE_CURL, MOVE_GRASS_WHISTLE, MOVE_AROMATHERAPY, MOVE_RAZOR_LEAF, MOVE_ROLLOUT, MOVE_FAKE_TEARS, MOVE_TICKLE, MOVE_WEATHER_BALL, MOVE_GRASSY_TERRAIN, MOVE_SWEET_SCENT, MOVE_FLOWER_SHIELD, MOVE_HEAL_PULSE, MOVE_HEALING_WISH, MOVE_SEED_BOMB, MOVE_NATURAL_GIFT, MOVE_NATURE_POWER,
		/*01D9 Ó£»¨±¦*/

		POKE_SHELLOS_BLUE + 20000, MOVE_MIST, MOVE_FISSURE, MOVE_YAWN, MOVE_MIRROR_COAT, MOVE_MEMENTO, MOVE_SPIT_UP, MOVE_CLEAR_SMOG, MOVE_ACID_ARMOR, MOVE_COUNTER, MOVE_AMNESIA, MOVE_SWALLOW, MOVE_TRUMP_CARD, MOVE_SLUDGE, MOVE_STOCKPILE, MOVE_BRINE, MOVE_CURSE,
		/*01DB ÎÞ¿Çº£ÍÃÀ¶*/

		POKE_DRIFLOON + 20000, MOVE_HYPNOSIS, MOVE_DISABLE, MOVE_HAZE, MOVE_MEMENTO, MOVE_WEATHER_BALL, MOVE_DEFOG, MOVE_CLEAR_SMOG, MOVE_TAILWIND, MOVE_BODY_SLAM, MOVE_DESTINY_BOND,
		/*01DE Æ®Æ®Çò*/

		POKE_BUNEARY + 20000, MOVE_CIRCLE_THROW, MOVE_SKY_UPPERCUT, MOVE_SWITCHEROO, MOVE_DOUBLE_HIT, MOVE_COPYCAT, MOVE_FAKE_OUT, MOVE_FAKE_TEARS, MOVE_LOW_KICK, MOVE_SWEET_KISS, MOVE_MUD_SPORT, MOVE_TEETER_DANCE, MOVE_COSMIC_POWER, MOVE_ENCORE, MOVE_OBLIVION_WING, MOVE_FOCUS_PUNCH, MOVE_FLAIL,
		/*01E0 ¾í¾í¶ú*/

		POKE_GLAMEOW + 20000, MOVE_QUICK_ATTACK, MOVE_ASSURANCE, MOVE_WAKEUP_SLAP, MOVE_FAKE_TEARS, MOVE_SAND_ATTACK, MOVE_SNATCH, MOVE_TAIL_WHIP, MOVE_BITE, MOVE_LAST_RESORT, MOVE_FLAIL,
		/*01E4 ÷ÈÁ¦ß÷*/

		POKE_CHINGLING + 20000, MOVE_HYPNOSIS, MOVE_DISABLE, MOVE_STORED_POWER, MOVE_WISH, MOVE_SKILL_SWAP, MOVE_COSMIC_POWER, MOVE_FUTURE_SIGHT, MOVE_RECOVER, MOVE_CURSE,
		/*01E6 ÁåîõÏì*/

		POKE_STUNKY + 20000, MOVE_PUNISHMENT, MOVE_LEER, MOVE_SCARY_FACE, MOVE_HAZE, MOVE_ASTONISH, MOVE_FLAME_BURST, MOVE_FOUL_PLAY, MOVE_DOUBLEEDGE, MOVE_IRON_TAIL, MOVE_PLAY_ROUGH, MOVE_CRUNCH, MOVE_PURSUIT, MOVE_SMOG,
		/*01E7 ³ô÷øàÛ*/

		POKE_BONSLY + 20000, MOVE_HARDEN, MOVE_DEFENSE_CURL, MOVE_ROLLOUT, MOVE_SAND_TOMB, MOVE_ENDURE, MOVE_HEADBUTT, MOVE_STEALTH_ROCK, MOVE_SELFDESTRUCT, MOVE_CURSE,
		/*01EB Åè²Å¹Ö*/

		POKE_MIMEJR + 20000, MOVE_ICY_WIND, MOVE_HYPNOSIS, MOVE_NASTY_PLOT, MOVE_WAKEUP_SLAP, MOVE_FAKE_OUT, MOVE_PSYCHIC_TERRAIN, MOVE_POWER_SPLIT, MOVE_MIMIC, MOVE_MAGIC_ROOM, MOVE_CONFUSE_RAY, MOVE_CHARM, MOVE_TRICK, MOVE_TEETER_DANCE, MOVE_FUTURE_SIGHT, MOVE_HEALING_WISH,
		/*01EC Ä§ÄáÄá*/

		POKE_HAPPINY + 20000, MOVE_HELPING_HAND, MOVE_AROMATHERAPY, MOVE_METRONOME, MOVE_PRESENT, MOVE_MUD_BOMB, MOVE_COUNTER, MOVE_ENDURE, MOVE_LAST_RESORT, MOVE_HEAL_BELL, MOVE_GRAVITY, MOVE_NATURAL_GIFT,
		/*01ED Ð¡¸£µ°*/

		POKE_CHATOT + 20000, MOVE_BOOMBURST, MOVE_SUPERSONIC, MOVE_STEEL_WING, MOVE_AGILITY, MOVE_NASTY_PLOT, MOVE_NIGHT_SHADE, MOVE_AIR_CUTTER, MOVE_SLEEP_TALK, MOVE_DEFOG, MOVE_ENCORE,
		/*01EE ñøÔëÄñ*/

		POKE_SPIRITOMB + 20000, MOVE_DISABLE, MOVE_NIGHTMARE, MOVE_PAIN_SPLIT, MOVE_IMPRISON, MOVE_FOUL_PLAY, MOVE_DESTINY_BOND, MOVE_SMOKESCREEN, MOVE_SHADOW_SNEAK, MOVE_CAPTIVATE, MOVE_GRUDGE,
		/*01EF »¨ÑÒ¹Ö*/

		POKE_GIBLE + 20000, MOVE_THRASH, MOVE_SCARY_FACE, MOVE_METAL_CLAW, MOVE_SAND_TOMB, MOVE_TWISTER, MOVE_DRAGON_BREATH, MOVE_MUD_SHOT, MOVE_OUTRAGE, MOVE_ROCK_CLIMB, MOVE_DOUBLEEDGE, MOVE_BODY_SLAM, MOVE_IRON_HEAD, MOVE_IRON_TAIL,
		/*01F0 Ô²Â½öè*/

		POKE_MUNCHLAX + 20000, MOVE_WHIRLWIND, MOVE_BELCH, MOVE_AFTER_YOU, MOVE_CHARM, MOVE_LICK, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_ZEN_HEADBUTT, MOVE_PURSUIT, MOVE_SELFDESTRUCT, MOVE_NATURAL_GIFT, MOVE_CURSE,
		/*01F3 Ð¡¿¨±ÈÊÞ*/

		POKE_RIOLU + 20000, MOVE_CIRCLE_THROW, MOVE_SKY_UPPERCUT, MOVE_HIGH_JUMP_KICK, MOVE_AGILITY, MOVE_METEOR_MASH, MOVE_BLAZE_KICK, MOVE_DETECT, MOVE_FOLLOW_ME, MOVE_CROSS_CHOP, MOVE_LOW_KICK, MOVE_IRON_DEFENSE, MOVE_MIND_READER, MOVE_CRUNCH, MOVE_BITE, MOVE_VACUUM_WAVE, MOVE_BULLET_PUNCH,
		/*01F4 ÀûÅ·Â·*/

		POKE_HIPPOPOTAS + 20000, MOVE_REVENGE, MOVE_WHIRLWIND, MOVE_SAND_TOMB, MOVE_SLEEP_TALK, MOVE_SPIT_UP, MOVE_BODY_SLAM, MOVE_SLACK_OFF, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_CURSE,
		/*01F6 É³ºÓÂí*/

		POKE_SKORUPI + 20000, MOVE_NIGHT_SLASH, MOVE_FEINT_ATTACK, MOVE_WHIRLWIND, MOVE_SCREECH, MOVE_POISON_TAIL, MOVE_AGILITY, MOVE_SLASH, MOVE_SAND_ATTACK, MOVE_CONFUSE_RAY, MOVE_TWINEEDLE, MOVE_IRON_TAIL, MOVE_PURSUIT,
		/*01F8 Ç¯Î²Ð«*/

		POKE_CROAGUNK + 20000, MOVE_DYNAMIC_PUNCH, MOVE_ACUPRESSURE, MOVE_WAKEUP_SLAP, MOVE_FAKE_OUT, MOVE_QUICK_GUARD, MOVE_ME_FIRST, MOVE_SMELLING_SALTS, MOVE_CROSS_CHOP, MOVE_COUNTER, MOVE_HEADBUTT, MOVE_DRAIN_PUNCH, MOVE_FEINT, MOVE_MEDITATE, MOVE_VACUUM_WAVE, MOVE_BULLET_PUNCH,
		/*01FA ²»Á¼ÍÜ*/

		POKE_CARNIVINE + 20000, MOVE_GRASS_WHISTLE, MOVE_SLEEP_POWDER, MOVE_WORRY_SEED, MOVE_RAZOR_LEAF, MOVE_RAGE_POWDER, MOVE_SYNTHESIS, MOVE_LEECH_SEED, MOVE_STUN_SPORE, MOVE_MAGICAL_LEAF, MOVE_SLAM, MOVE_ACID_SPRAY, MOVE_GIGA_DRAIN,
		/*01FC ¼âÑÀÁý*/

		POKE_FINNEON + 20000, MOVE_AGILITY, MOVE_PSYBEAM, MOVE_AURORA_BEAM, MOVE_TICKLE, MOVE_CONFUSE_RAY, MOVE_CHARM, MOVE_AQUA_TAIL, MOVE_SWEET_KISS, MOVE_SIGNAL_BEAM, MOVE_BRINE, MOVE_SPLASH, MOVE_FLAIL,
		/*01FD Ó«¹âÓã*/

		POKE_MANTYKE + 20000, MOVE_WIDE_GUARD, MOVE_HAZE, MOVE_MIRROR_COAT, MOVE_TWISTER, MOVE_SLAM, MOVE_HYDRO_PUMP, MOVE_TAILWIND, MOVE_AMNESIA, MOVE_MUD_SPORT, MOVE_WATER_SPORT, MOVE_SIGNAL_BEAM, MOVE_SPLASH,
		/*01FF Ð¡Çò·ÉÓã*/

		POKE_SNOVER + 20000, MOVE_MIST, MOVE_STOMP, MOVE_SKULL_BASH, MOVE_LEECH_SEED, MOVE_MAGICAL_LEAF, MOVE_DOUBLEEDGE, MOVE_GROWTH, MOVE_AVALANCHE, MOVE_BULLET_SEED, MOVE_SEED_BOMB, MOVE_NATURAL_GIFT,
		/*0200 Ñ©óÒ¹Ö*/

		POKE_SNIVY + 20000, MOVE_GLARE, MOVE_MEAN_LOOK, MOVE_MIRROR_COAT, MOVE_TWISTER, MOVE_MAGICAL_LEAF, MOVE_GRASSY_TERRAIN, MOVE_SWEET_SCENT, MOVE_IRON_TAIL, MOVE_CAPTIVATE, MOVE_PURSUIT, MOVE_NATURAL_GIFT,
		/*0224 ÌÙÌÙÉß*/

		POKE_TEPIG + 20000, MOVE_THRASH, MOVE_YAWN, MOVE_COVET, MOVE_ENDEAVOR, MOVE_SUPERPOWER, MOVE_SLEEP_TALK, MOVE_BURN_UP, MOVE_BODY_SLAM, MOVE_SUCKER_PUNCH, MOVE_MAGNITUDE, MOVE_HEAVY_SLAM, MOVE_CURSE,
		/*0227 Å¯Å¯Öí*/

		POKE_OSHAWOTT + 20000, MOVE_NIGHT_SLASH, MOVE_SCREECH, MOVE_ASSURANCE, MOVE_COPYCAT, MOVE_DETECT, MOVE_AIR_SLASH, MOVE_SACRED_SWORD, MOVE_TRUMP_CARD, MOVE_BRINE,
		/*022A Ë®Ë®Ì¡*/

		POKE_PATRAT + 20000, MOVE_REVENGE, MOVE_SCREECH, MOVE_ASSURANCE, MOVE_TEARFUL_LOOK, MOVE_FORESIGHT, MOVE_IRON_TAIL, MOVE_BULLET_SEED, MOVE_FLAIL, MOVE_PURSUIT,
		/*022D Ì½Ì½Êó*/

		POKE_LILLIPUP + 20000, MOVE_ICE_FANG, MOVE_YAWN, MOVE_FIRE_FANG, MOVE_PSYCHIC_FANGS, MOVE_THUNDER_FANG, MOVE_AFTER_YOU, MOVE_SAND_ATTACK, MOVE_CHARM, MOVE_LICK, MOVE_ENDURE, MOVE_HOWL, MOVE_MUDSLAP, MOVE_PURSUIT,
		/*022F Ð¡Ô¼¿Ë*/

		POKE_PURRLOIN + 20000, MOVE_FEINT_ATTACK, MOVE_COPYCAT, MOVE_YAWN, MOVE_FAKE_TEARS, MOVE_PAY_DAY, MOVE_COVET, MOVE_FOUL_PLAY, MOVE_CHARM, MOVE_ENCORE,
		/*0232 °ÇÊÖÃ¨*/

		POKE_PANSAGE + 20000, MOVE_ROLE_PLAY, MOVE_GRASS_WHISTLE, MOVE_LEAF_STORM, MOVE_NASTY_PLOT, MOVE_SPIKY_SHIELD, MOVE_ASTONISH, MOVE_COVET, MOVE_DISARMING_VOICE, MOVE_MAGICAL_LEAF, MOVE_TICKLE, MOVE_LOW_KICK, MOVE_BULLET_SEED,
		/*0234 »¨Ò¬ºï*/

		POKE_PANSEAR + 20000, MOVE_ROLE_PLAY, MOVE_BELCH, MOVE_NASTY_PLOT, MOVE_FIRE_PUNCH, MOVE_FIRE_SPIN, MOVE_ASTONISH, MOVE_COVET, MOVE_DISARMING_VOICE, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_HEAT_WAVE, MOVE_FLARE_BLITZ, MOVE_LOW_KICK,
		/*0236 ±¬Ïãºï*/

		POKE_PANPOUR + 20000, MOVE_ROLE_PLAY, MOVE_NASTY_PLOT, MOVE_ASTONISH, MOVE_COVET, MOVE_DISARMING_VOICE, MOVE_TICKLE, MOVE_AQUA_RING, MOVE_AQUA_TAIL, MOVE_HYDRO_PUMP, MOVE_LOW_KICK, MOVE_MUD_SPORT,
		/*0238 ÀäË®ºï*/

		POKE_MUNNA + 20000, MOVE_HELPING_HAND, MOVE_SWIFT, MOVE_BATON_PASS, MOVE_SLEEP_TALK, MOVE_SECRET_POWER, MOVE_MAGIC_COAT, MOVE_BARRIER, MOVE_SONIC_BOOM, MOVE_HEALING_WISH, MOVE_CURSE,
		/*023A Ê³ÃÎÃÎ*/

		POKE_PIDOVE + 20000, MOVE_NIGHT_SLASH, MOVE_UPROAR, MOVE_MORNING_SUN, MOVE_BESTOW, MOVE_HYPNOSIS, MOVE_STEEL_WING, MOVE_WISH, MOVE_LUCKY_CHANT,
		/*023C ¶¹¶¹¸ë*/

		POKE_BLITZLE + 20000, MOVE_SCREECH, MOVE_SHOCK_WAVE, MOVE_DOUBLE_KICK, MOVE_RAGE, MOVE_TAKE_DOWN, MOVE_SAND_ATTACK, MOVE_SNATCH, MOVE_ME_FIRST, MOVE_DOUBLEEDGE, MOVE_ENDURE, MOVE_FEINT,
		/*023F °ß°ßÂí*/

		POKE_ROGGENROLA + 20000, MOVE_WIDE_GUARD, MOVE_TAKE_DOWN, MOVE_AUTOTOMIZE, MOVE_LOCKON, MOVE_ROCK_TOMB, MOVE_MAGNITUDE, MOVE_HEAVY_SLAM, MOVE_GRAVITY, MOVE_CURSE,
		/*0241 Ê¯Íè×Ó*/

		POKE_WOOBAT + 20000, MOVE_HELPING_HAND, MOVE_SUPERSONIC, MOVE_FLATTER, MOVE_VENOM_DRENCH, MOVE_STORED_POWER, MOVE_FAKE_TEARS, MOVE_PSYCHO_SHIFT, MOVE_KNOCK_OFF, MOVE_CHARM, MOVE_SYNCHRONOISE, MOVE_CAPTIVATE, MOVE_ROOST,
		/*0244 ¹ö¹öòùòð*/

		POKE_DRILBUR + 20000, MOVE_EARTH_POWER, MOVE_SUBMISSION, MOVE_RAPID_SPIN, MOVE_SKULL_BASH, MOVE_METAL_SOUND, MOVE_ROCK_CLIMB, MOVE_CRUSH_CLAW, MOVE_IRON_DEFENSE,
		/*0246 ÂÝ¶¤µØÊó*/

		POKE_AUDINO + 20000, MOVE_BESTOW, MOVE_YAWN, MOVE_SLEEP_TALK, MOVE_WISH, MOVE_AMNESIA, MOVE_SWEET_KISS, MOVE_DRAINING_KISS, MOVE_LUCKY_CHANT, MOVE_ENCORE, MOVE_HEAL_BELL, MOVE_HEALING_WISH,
		/*0248 ²î²»¶àÍÞÍÞ*/

		POKE_TIMBURR + 20000, MOVE_FORCE_PALM, MOVE_WIDE_GUARD, MOVE_DETECT, MOVE_COMET_PUNCH, MOVE_REVERSAL, MOVE_SMELLING_SALTS, MOVE_FORESIGHT, MOVE_COUNTER, MOVE_ENDURE, MOVE_DRAIN_PUNCH, MOVE_MACH_PUNCH, MOVE_OBLIVION_WING,
		/*0249 °áÔËÐ¡½³*/

		POKE_TYMPOLE + 20000, MOVE_MIST, MOVE_SNORE, MOVE_EARTH_POWER, MOVE_VENOM_DRENCH, MOVE_REFRESH, MOVE_SLEEP_TALK, MOVE_MUD_BOMB, MOVE_AFTER_YOU, MOVE_WATER_PULSE, MOVE_MUD_SPORT,
		/*024C Ô²òòò½*/

		POKE_SEWADDLE + 20000, MOVE_CAMOUFLAGE, MOVE_SCREECH, MOVE_AGILITY, MOVE_BATON_PASS, MOVE_AIR_SLASH, MOVE_ME_FIRST, MOVE_GRASSY_TERRAIN, MOVE_MIND_READER, MOVE_RAZOR_WIND, MOVE_SILVER_WIND,
		/*0251 ³æ±¦°ü*/

		POKE_VENIPEDE + 20000, MOVE_TOXIC_SPIKES, MOVE_PIN_MISSILE, MOVE_TAKE_DOWN, MOVE_ROCK_CLIMB, MOVE_SPIKES, MOVE_TWINEEDLE,
		/*0254 °Ù×ãòÚò¼*/

		POKE_COTTONEE + 20000, MOVE_MISTY_TERRAIN, MOVE_GRASS_WHISTLE, MOVE_SWITCHEROO, MOVE_WORRY_SEED, MOVE_FAKE_TEARS, MOVE_MEMENTO, MOVE_TICKLE, MOVE_BEAT_UP, MOVE_CAPTIVATE, MOVE_ENCORE, MOVE_NATURAL_GIFT,
		/*0257 Ä¾ÃÞÇò*/

		POKE_PETILIL + 20000, MOVE_GRASS_WHISTLE, MOVE_WORRY_SEED, MOVE_BIDE, MOVE_CHARM, MOVE_SWEET_SCENT, MOVE_ENDURE, MOVE_ENCORE, MOVE_INGRAIN, MOVE_HEALING_WISH, MOVE_NATURAL_GIFT,
		/*0259 °ÙºÏ¸ùÍÞÍÞ*/

		POKE_BASCULIN_RED + 20000, MOVE_REVENGE, MOVE_WHIRLPOOL, MOVE_RAGE, MOVE_SWIFT, MOVE_AGILITY, MOVE_MUD_SHOT, MOVE_BUBBLE_BEAM, MOVE_HEAD_SMASH, MOVE_BRINE, MOVE_MUDDY_WATER,
		/*025B Ò°ÂùöÔÓãºì*/

		POKE_SANDILE + 20000, MOVE_UPROAR, MOVE_MEAN_LOOK, MOVE_FIRE_FANG, MOVE_FOCUS_ENERGY, MOVE_THUNDER_FANG, MOVE_ROCK_CLIMB, MOVE_ME_FIRST, MOVE_DOUBLEEDGE, MOVE_COUNTER, MOVE_BEAT_UP, MOVE_POWER_TRIP, MOVE_PURSUIT,
		/*025C ºÚÑÛöù*/

		POKE_DARUMAKA + 20000, MOVE_HAMMER_ARM, MOVE_YAWN, MOVE_FLAME_WHEEL, MOVE_FOCUS_ENERGY, MOVE_TAKE_DOWN, MOVE_SLEEP_TALK, MOVE_SNATCH, MOVE_EXTRASENSORY, MOVE_ENDURE, MOVE_ENCORE, MOVE_FOCUS_PUNCH,
		/*025F »ðºì²»µ¹ÎÌ*/

		POKE_MARACTUS + 20000, MOVE_GRASS_WHISTLE, MOVE_BOUNCE, MOVE_WORRY_SEED, MOVE_LEECH_SEED, MOVE_WOOD_HAMMER, MOVE_GRASSY_TERRAIN, MOVE_SPIKES, MOVE_BULLET_SEED, MOVE_SEED_BOMB,
		/*0261 É³ÁåÏÉÈËÕÆ*/

		POKE_DWEBBLE + 20000, MOVE_NIGHT_SLASH, MOVE_BLOCK, MOVE_ROTOTILLER, MOVE_WIDE_GUARD, MOVE_SAND_TOMB, MOVE_SPIKES, MOVE_COUNTER, MOVE_IRON_DEFENSE, MOVE_ENDURE, MOVE_CURSE,
		/*0262 Ê¯¾ÓÐ·*/

		POKE_SCRAGGY + 20000, MOVE_ICE_PUNCH, MOVE_FEINT_ATTACK, MOVE_FIRE_PUNCH, MOVE_FAKE_OUT, MOVE_DETECT, MOVE_QUICK_GUARD, MOVE_THUNDER_PUNCH, MOVE_DRAGON_DANCE, MOVE_COUNTER, MOVE_AMNESIA, MOVE_ACID_SPRAY, MOVE_DRAIN_PUNCH, MOVE_ZEN_HEADBUTT, MOVE_OBLIVION_WING,
		/*0264 »¬»¬Ð¡×Ó*/

		POKE_SIGILYPH + 20000, MOVE_STORED_POWER, MOVE_STEEL_WING, MOVE_PSYCHO_SHIFT, MOVE_SKILL_SWAP, MOVE_ROOST, MOVE_FUTURE_SIGHT, MOVE_ANCIENT_POWER,
		/*0266 ÏóÕ÷Äñ*/

		POKE_YAMASK + 20000, MOVE_DISABLE, MOVE_TOXIC_SPIKES, MOVE_NIGHTMARE, MOVE_IMPRISON, MOVE_NASTY_PLOT, MOVE_HEAL_BLOCK, MOVE_FAKE_TEARS, MOVE_ALLY_SWITCH, MOVE_MEMENTO, MOVE_ENDURE, MOVE_CRAFTY_SHIELD,
		/*0267 ¿Þ¿ÞÃæ¾ß*/

		POKE_TIRTOUGA + 20000, MOVE_WHIRLPOOL, MOVE_GUARD_SWAP, MOVE_ROCK_THROW, MOVE_KNOCK_OFF, MOVE_BIDE, MOVE_SLAM, MOVE_LIQUIDATION, MOVE_WATER_PULSE, MOVE_BODY_SLAM, MOVE_IRON_DEFENSE, MOVE_FLAIL,
		/*0269 Ô­¸Çº£¹ê*/

		POKE_ARCHEN + 20000, MOVE_EARTH_POWER, MOVE_SWITCHEROO, MOVE_STEEL_WING, MOVE_ALLY_SWITCH, MOVE_DRAGON_PULSE, MOVE_KNOCK_OFF, MOVE_DEFOG, MOVE_HEAD_SMASH, MOVE_BITE,
		/*026B Ê¼×æÐ¡Äñ*/

		POKE_TRUBBISH + 20000, MOVE_ROLLOUT, MOVE_HAZE, MOVE_SAND_ATTACK, MOVE_SPIKES, MOVE_AUTOTOMIZE, MOVE_MUD_SPORT, MOVE_ROCK_BLAST, MOVE_SELFDESTRUCT, MOVE_CURSE,
		/*026D ÆÆÆÆ´ü*/

		POKE_ZORUA + 20000, MOVE_DARK_PULSE, MOVE_COPYCAT, MOVE_DETECT, MOVE_MEMENTO, MOVE_SNATCH, MOVE_EXTRASENSORY, MOVE_COUNTER, MOVE_SUCKER_PUNCH, MOVE_CAPTIVATE,
		/*026F Ë÷ÂÞÑÇ*/

		POKE_MINCCINO + 20000, MOVE_FAKE_TEARS, MOVE_SLEEP_TALK, MOVE_KNOCK_OFF, MOVE_AQUA_TAIL, MOVE_IRON_TAIL, MOVE_ENDURE, MOVE_TAIL_WHIP, MOVE_MUDSLAP, MOVE_FLAIL,
		/*0271 ÅÝÄ­ÀõÊó*/

		POKE_GOTHITA + 20000, MOVE_UPROAR, MOVE_DARK_PULSE, MOVE_MEAN_LOOK, MOVE_MIRROR_COAT, MOVE_MIRACLE_EYE, MOVE_CAPTIVATE, MOVE_HEAL_PULSE,
		/*0273 ¸çµÂ±¦±¦*/

		POKE_SOLOSIS + 20000, MOVE_HELPING_HAND, MOVE_IMPRISON, MOVE_NIGHT_SHADE, MOVE_ASTONISH, MOVE_SECRET_POWER, MOVE_CONFUSE_RAY, MOVE_ACID_ARMOR, MOVE_TRICK,
		/*0276 µ¥ÂÑÏ¸°ûÇò*/

		POKE_DUCKLETT + 20000, MOVE_STEEL_WING, MOVE_AIR_CUTTER, MOVE_GUST, MOVE_ME_FIRST, MOVE_AQUA_JET, MOVE_MUD_SPORT, MOVE_LUCKY_CHANT, MOVE_BRINE, MOVE_MIRROR_MOVE,
		/*0279 Ñ¼±¦±¦*/

		POKE_VANILLITE + 20000, MOVE_ICE_SHARD, MOVE_MAGNET_RISE, MOVE_IMPRISON, MOVE_AUTOTOMIZE, MOVE_WATER_PULSE, MOVE_IRON_DEFENSE, MOVE_POWDER_SNOW, MOVE_NATURAL_GIFT,
		/*027B ÃÔÄã±ù*/

		POKE_DEERLING_SPRING + 20000, MOVE_GRASS_WHISTLE, MOVE_WORRY_SEED, MOVE_AGILITY, MOVE_SYNTHESIS, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_SLEEP_TALK, MOVE_ODOR_SLEUTH, MOVE_HEADBUTT, MOVE_NATURAL_GIFT,
		/*027E ËÄ¼¾Â¹´º*/

		POKE_EMOLGA + 20000, MOVE_ION_DELUGE, MOVE_SHOCK_WAVE, MOVE_BATON_PASS, MOVE_ASTONISH, MOVE_COVET, MOVE_AIR_SLASH, MOVE_TICKLE, MOVE_CHARM, MOVE_SPEED_SWAP, MOVE_IRON_TAIL, MOVE_ROOST,
		/*0280 µç·ÉÊó*/

		POKE_KARRABLAST + 20000, MOVE_MEGAHORN, MOVE_BUG_BITE, MOVE_FEINT_ATTACK, MOVE_SCREECH, MOVE_HORN_ATTACK, MOVE_KNOCK_OFF, MOVE_COUNTER, MOVE_DRILL_RUN, MOVE_PURSUIT,
		/*0281 ¸Ç¸Ç³æ*/

		POKE_FOONGUS + 20000, MOVE_DEFENSE_CURL, MOVE_POISON_POWDER, MOVE_ROLLOUT, MOVE_STUN_SPORE, MOVE_GROWTH, MOVE_BODY_SLAM, MOVE_ENDURE, MOVE_GASTRO_ACID,
		/*0283 °¥Ñ½Çò¹½*/

		POKE_FRILLISH_MALE + 20000, MOVE_MIST, MOVE_CONSTRICT, MOVE_PAIN_SPLIT, MOVE_CONFUSE_RAY, MOVE_ACID_ARMOR, MOVE_RECOVER,
		/*0285 ÇáÆ®Æ®À¶*/

		POKE_ALOMOMOLA + 20000, MOVE_MIST, MOVE_PAIN_SPLIT, MOVE_REFRESH, MOVE_MIRROR_COAT, MOVE_TICKLE, MOVE_ENDURE,
		/*0287 ±£Ä·Âü²¨*/

		POKE_JOLTIK + 20000, MOVE_CAMOUFLAGE, MOVE_FEINT_ATTACK, MOVE_DISABLE, MOVE_POISON_STING, MOVE_PIN_MISSILE, MOVE_LUNGE, MOVE_ROCK_CLIMB, MOVE_CROSS_POISON, MOVE_PURSUIT,
		/*0288 µçµç³æ*/

		POKE_FERROSEED + 20000, MOVE_WORRY_SEED, MOVE_LEECH_SEED, MOVE_ROCK_CLIMB, MOVE_SPIKES, MOVE_ACID_SPRAY, MOVE_STEALTH_ROCK, MOVE_BULLET_SEED, MOVE_SEED_BOMB, MOVE_GRAVITY,
		/*028A ÖÖ×ÓÌúÇò*/

		POKE_ELGYEM + 20000, MOVE_DISABLE, MOVE_GUARD_SWAP, MOVE_NASTY_PLOT, MOVE_ALLY_SWITCH, MOVE_ASTONISH, MOVE_POWER_SWAP, MOVE_BARRIER, MOVE_TELEPORT, MOVE_SKILL_SWAP, MOVE_COSMIC_POWER,
		/*0292 Ð¡»Ò¹Ö*/

		POKE_LITWICK + 20000, MOVE_HAZE, MOVE_POWER_SPLIT, MOVE_CLEAR_SMOG, MOVE_HEAT_WAVE, MOVE_ACID_ARMOR, MOVE_ACID, MOVE_ENDURE, MOVE_CAPTIVATE,
		/*0294 Öò¹âÁé*/

		POKE_AXEW + 20000, MOVE_NIGHT_SLASH, MOVE_HARDEN, MOVE_FOCUS_ENERGY, MOVE_DRAGON_PULSE, MOVE_ENDEAVOR, MOVE_REVERSAL, MOVE_COUNTER, MOVE_IRON_TAIL, MOVE_ENDURE, MOVE_RAZOR_WIND,
		/*0297 ÑÀÑÀ*/

		POKE_CUBCHOO + 20000, MOVE_NIGHT_SLASH, MOVE_ICE_PUNCH, MOVE_ASSURANCE, MOVE_YAWN, MOVE_SLEEP_TALK, MOVE_PLAY_ROUGH, MOVE_AVALANCHE, MOVE_ENCORE, MOVE_FOCUS_PUNCH,
		/*029A ÅçÌçÐÜ*/

		POKE_SHELMET + 20000, MOVE_TOXIC_SPIKES, MOVE_GUARD_SPLIT, MOVE_BATON_PASS, MOVE_SPIKES, MOVE_DOUBLEEDGE, MOVE_ENDURE, MOVE_MIND_READER, MOVE_FEINT, MOVE_ENCORE, MOVE_MUDSLAP, MOVE_PURSUIT,
		/*029D Ð¡×ìÎÏ*/

		POKE_STUNFISK + 20000, MOVE_EARTH_POWER, MOVE_SPARK, MOVE_SHOCK_WAVE, MOVE_PAIN_SPLIT, MOVE_EERIE_IMPULSE, MOVE_YAWN, MOVE_ASTONISH, MOVE_REFLECT_TYPE, MOVE_SLEEP_TALK, MOVE_ME_FIRST, MOVE_SPITE, MOVE_CURSE,
		/*029F Äà°ÍÓã*/

		POKE_MIENFOO + 20000, MOVE_ALLY_SWITCH, MOVE_BATON_PASS, MOVE_VITAL_THROW, MOVE_KNOCK_OFF, MOVE_ME_FIRST, MOVE_SMELLING_SALTS, MOVE_LOW_KICK, MOVE_ENDURE, MOVE_FEINT,
		/*02A0 ¹¦·ò÷ø*/

		POKE_DRUDDIGON + 20000, MOVE_FEINT_ATTACK, MOVE_GLARE, MOVE_POISON_TAIL, MOVE_FIRE_FANG, MOVE_METAL_CLAW, MOVE_THUNDER_FANG, MOVE_SNATCH, MOVE_CRUSH_CLAW, MOVE_IRON_TAIL, MOVE_SUCKER_PUNCH, MOVE_PURSUIT,
		/*02A2 ³àÃæÁú*/

		POKE_PAWNIARD + 20000, MOVE_REVENGE, MOVE_MEAN_LOOK, MOVE_PSYCHO_CUT, MOVE_QUICK_GUARD, MOVE_HEADBUTT, MOVE_SUCKER_PUNCH, MOVE_STEALTH_ROCK, MOVE_PURSUIT,
		/*02A5 ¾Ôµ¶Ð¡±ø*/

		POKE_BOUFFALANT + 20000, MOVE_STOMP, MOVE_BELCH, MOVE_SKULL_BASH, MOVE_COTTON_GUARD, MOVE_MUD_SHOT, MOVE_ROCK_CLIMB, MOVE_AMNESIA, MOVE_IRON_HEAD, MOVE_HEADBUTT, MOVE_MUDSLAP,
		/*02A7 ±¬Õ¨Í·Ë®Å£*/

		POKE_VULLABY + 20000, MOVE_STEEL_WING, MOVE_SCARY_FACE, MOVE_MEAN_LOOK, MOVE_FAKE_TEARS, MOVE_KNOCK_OFF, MOVE_FOUL_PLAY, MOVE_ROOST,
		/*02AA ÍºÓ¥Ñ¾Í·*/

		POKE_HEATMOR + 20000, MOVE_NIGHT_SLASH, MOVE_FEINT_ATTACK, MOVE_BELCH, MOVE_WRAP, MOVE_SLEEP_TALK, MOVE_TICKLE, MOVE_HEAT_WAVE, MOVE_BODY_SLAM, MOVE_SUCKER_PUNCH, MOVE_PURSUIT, MOVE_CURSE,
		/*02AC ÈÛÒÏÊÞ*/

		POKE_DURANT + 20000, MOVE_FEINT_ATTACK, MOVE_SCREECH, MOVE_BATON_PASS, MOVE_THUNDER_FANG, MOVE_ROCK_CLIMB, MOVE_ENDURE,
		/*02AD ÌúÒÏ*/

		POKE_DEINO + 20000, MOVE_ICE_FANG, MOVE_SCREECH, MOVE_BELCH, MOVE_EARTH_POWER, MOVE_ASSURANCE, MOVE_DARK_PULSE, MOVE_DOUBLE_HIT, MOVE_FIRE_FANG, MOVE_ASTONISH, MOVE_THUNDER_FANG, MOVE_HEAD_SMASH,
		/*02AE µ¥Ê×Áú*/

		POKE_LARVESTA + 20000, MOVE_HARDEN, MOVE_MORNING_SUN, MOVE_MAGNET_RISE, MOVE_FORESIGHT, MOVE_ENDURE, MOVE_STRING_SHOT, MOVE_ZEN_HEADBUTT,
		/*02B1 È¼ÉÕ³æ*/

		POKE_CHESPIN + 20000, MOVE_DEFENSE_CURL, MOVE_BELLY_DRUM, MOVE_SYNTHESIS, MOVE_ROLLOUT, MOVE_QUICK_GUARD, MOVE_SPIKES, MOVE_OBLIVION_WING, MOVE_CURSE,
		/*02BF ¹þÁ¦Àõ*/

		POKE_FENNEKIN + 20000, MOVE_HYPNOSIS, MOVE_PSYCHIC_TERRAIN, MOVE_MAGIC_COAT, MOVE_WISH, MOVE_HEAT_WAVE,
		/*02C2 »ðºüÀê*/

		POKE_FROAKIE + 20000, MOVE_CAMOUFLAGE, MOVE_BESTOW, MOVE_TOXIC_SPIKES, MOVE_MUD_SPORT, MOVE_WATER_SPORT, MOVE_MIND_READER, MOVE_OBLIVION_WING,
		/*02C5 ßÉßÉÅÝÍÜ*/

		POKE_BUNNELBY + 20000, MOVE_DEFENSE_CURL, MOVE_ROLLOUT, MOVE_SPIKES,
		/*02C8 ¾ò¾òÍÃ*/

		POKE_FLETCHLING + 20000, MOVE_QUICK_GUARD, MOVE_SNATCH, MOVE_TAILWIND,
		/*02CA Ð¡¼ýÈ¸*/

		POKE_SCATTERBUG + 20000, MOVE_POISON_POWDER, MOVE_RAGE_POWDER, MOVE_STUN_SPORE,
		/*02CD ·Ûµû³æ*/

		POKE_LITLEO + 20000, MOVE_YAWN, MOVE_FIRE_SPIN, MOVE_SNATCH, MOVE_FLARE_BLITZ, MOVE_ENTRAINMENT,
		/*02D0 Ð¡Ê¨Ê¨*/

		POKE_FLABEBE_RED + 20000, MOVE_CAMOUFLAGE, MOVE_COPYCAT, MOVE_TEARFUL_LOOK, MOVE_CAPTIVATE,
		/*02D2 »¨ÝíÝíºì*/

		POKE_SKIDDO + 20000, MOVE_DEFENSE_CURL, MOVE_ROLLOUT, MOVE_MILK_DRINK, MOVE_GRASSY_TERRAIN,
		/*02D5 ×øÆïÐ¡Ñò*/

		POKE_PANCHAM + 20000, MOVE_QUICK_GUARD, MOVE_FOUL_PLAY, MOVE_ME_FIRST, MOVE_STORM_THROW, MOVE_POWER_TRIP, MOVE_QUASH,
		/*02D7 ÍçÆ¤ÐÜÃ¨*/

		POKE_FURFROU + 20000, MOVE_ROLE_PLAY, MOVE_REFRESH, MOVE_MIMIC, MOVE_CAPTIVATE, MOVE_WORK_UP,
		/*02D9 ¶àÀöÃ×ÑÇ*/

		POKE_ESPURR + 20000, MOVE_YAWN, MOVE_ASSIST, MOVE_BARRIER, MOVE_TRICK,
		/*02DA Ãîß÷*/

		POKE_HONEDGE + 20000, MOVE_WIDE_GUARD, MOVE_METAL_SOUND, MOVE_DESTINY_BOND, MOVE_SHADOW_SNEAK,
		/*02DC ¶À½£ÇÊ*/

		POKE_SPRITZEE + 20000, MOVE_DISABLE, MOVE_NASTY_PLOT, MOVE_REFRESH, MOVE_WISH, MOVE_CAPTIVATE,
		/*02DF ·ÛÏãÏã*/

		POKE_SWIRLIX + 20000, MOVE_COPYCAT, MOVE_BELLY_DRUM, MOVE_YAWN, MOVE_STICKY_WEB, MOVE_AFTER_YOU,
		/*02E1 ÃàÃàÅÝÜ½*/

		POKE_INKAY + 20000, MOVE_CAMOUFLAGE, MOVE_FLATTER, MOVE_SIMPLE_BEAM, MOVE_GUARD_SWAP, MOVE_POWER_SPLIT, MOVE_DESTINY_BOND,
		/*02E3 ºÃÀ²öÏ*/

		POKE_BINACLE + 20000, MOVE_HELPING_HAND, MOVE_SWITCHEROO, MOVE_TICKLE, MOVE_WATER_SPORT,
		/*02E5 ¹ê½Å½Å*/

		POKE_SKRELP + 20000, MOVE_TOXIC_SPIKES, MOVE_VENOM_DRENCH, MOVE_HAZE, MOVE_ACID_ARMOR, MOVE_PLAY_ROUGH,
		/*02E7 À¬À¬Ôå*/

		POKE_CLAUNCHER + 20000, MOVE_HELPING_HAND, MOVE_AQUA_JET, MOVE_ENDURE, MOVE_CRABHAMMER, MOVE_ENTRAINMENT,
		/*02E9 Ìú±ÛÇ¹Ïº*/

		POKE_HELIOPTILE + 20000, MOVE_CAMOUFLAGE, MOVE_GLARE, MOVE_ELECTRIC_TERRAIN, MOVE_AGILITY,
		/*02EB É¡µçòá*/

		POKE_TYRUNT + 20000, MOVE_ICE_FANG, MOVE_FIRE_FANG, MOVE_POISON_FANG, MOVE_THUNDER_FANG, MOVE_DRAGON_DANCE, MOVE_ROCK_POLISH, MOVE_CURSE,
		/*02ED ±¦±¦±©Áú*/

		POKE_AMAURA + 20000, MOVE_MAGNET_RISE, MOVE_DISCHARGE, MOVE_HAZE, MOVE_MIRROR_COAT, MOVE_BARRIER,
		/*02EF ±ùÑ©Áú*/

		POKE_HAWLUCHA + 20000, MOVE_AGILITY, MOVE_ALLY_SWITCH, MOVE_BATON_PASS, MOVE_QUICK_GUARD, MOVE_ME_FIRST, MOVE_MUD_SPORT, MOVE_FEINT, MOVE_ENTRAINMENT,
		/*02F2 Ë¤½ÇÓ¥ÈË*/

		POKE_DEDENNE + 20000, MOVE_HELPING_HAND, MOVE_EERIE_IMPULSE, MOVE_COVET, MOVE_TEARFUL_LOOK, MOVE_NATURAL_GIFT,
		/*02F3 ßËßËÊó*/

		POKE_GOOMY + 20000, MOVE_POISON_TAIL, MOVE_ACID_ARMOR, MOVE_COUNTER, MOVE_IRON_TAIL, MOVE_ENDURE, MOVE_CURSE,
		/*02F5 ð¤ð¤±¦*/

		POKE_KLEFKI + 20000, MOVE_SWITCHEROO, MOVE_LOCKON, MOVE_IRON_DEFENSE, MOVE_THIEF,
		/*02F8 Ô¿È¦¶ù*/

		POKE_PHANTUMP + 20000, MOVE_BESTOW, MOVE_VENOM_DRENCH, MOVE_IMPRISON, MOVE_GRUDGE, MOVE_OBLIVION_WING,
		/*02F9 Ð¡Ä¾Áé*/

		POKE_PUMPKABOO + 20000, MOVE_BESTOW, MOVE_DISABLE, MOVE_DESTINY_BOND, MOVE_CURSE,
		/*02FB ÄÏ¹Ï¾«*/

		POKE_BERGMITE + 20000, MOVE_MIST, MOVE_MIRROR_COAT, MOVE_BARRIER, MOVE_RECOVER,
		/*02FD ±ù±¦*/

		POKE_NOIBAT + 20000, MOVE_SWITCHEROO, MOVE_OUTRAGE, MOVE_SNATCH, MOVE_TAILWIND,
		/*02FF ÎËòð*/

		POKE_ROWLET + 20000, MOVE_HAZE, MOVE_BATON_PASS, MOVE_OMINOUS_WIND, MOVE_CONFUSE_RAY, MOVE_DEFOG, MOVE_CURSE,
		/*0307 Ä¾Ä¾èÉ*/

		POKE_LITTEN + 20000, MOVE_REVENGE, MOVE_NASTY_PLOT, MOVE_FAKE_OUT, MOVE_HEAT_WAVE, MOVE_BODY_SLAM, MOVE_POWER_TRIP, MOVE_CRUNCH,
		/*030A »ð°ßß÷*/

		POKE_POPPLIO + 20000, MOVE_AROMATIC_MIST, MOVE_PERISH_SONG, MOVE_WONDER_ROOM, MOVE_CHARM, MOVE_AQUA_RING, MOVE_AMNESIA,
		/*030D ÇòÇòº£Ê¨*/

		POKE_PIKIPEK + 20000, MOVE_BOOMBURST, MOVE_UPROAR, MOVE_TAILWIND, MOVE_MIRROR_MOVE, MOVE_BRAVE_BIRD,
		/*0310 Ð¡óÆ¶ù*/

		POKE_YUNGOOS + 20000, MOVE_REVENGE, MOVE_ICE_FANG, MOVE_FIRE_FANG, MOVE_THUNDER_FANG, MOVE_LAST_RESORT,
		/*0313 Ã¨÷øÉÙ*/

		POKE_GRUBBIN + 20000, MOVE_HARDEN, MOVE_ELECTROWEB, MOVE_MUD_SHOT, MOVE_ENDURE,
		/*0315 Ç¿ò¦¼¦Ä¸³æ*/

		POKE_CRABRAWLER + 20000, MOVE_WIDE_GUARD, MOVE_ENDEAVOR, MOVE_SUPERPOWER, MOVE_AMNESIA,
		/*0318 ºÃÊ¤Ð·*/

		POKE_ORICORIO_META + 20000, MOVE_SAFEGUARD, MOVE_TAILWIND, MOVE_CAPTIVATE, MOVE_PLUCK,
		/*031A »¨ÎèÄñ»ð*/

		POKE_CUTIEFLY + 20000, MOVE_BESTOW, MOVE_POWDER, MOVE_BATON_PASS, MOVE_STICKY_WEB, MOVE_SPEED_SWAP, MOVE_SKILL_SWAP, MOVE_MOONBLAST,
		/*031B ÃÈòµ*/

		POKE_ROCKRUFF + 20000, MOVE_THRASH, MOVE_FIRE_FANG, MOVE_THUNDER_FANG, MOVE_CRUSH_CLAW, MOVE_SUCKER_PUNCH,
		/*031D ÑÒ¹·¹·*/

		POKE_WISHIWASHI + 20000, MOVE_MIST, MOVE_WHIRLPOOL, MOVE_WATER_PULSE, MOVE_WATER_SPORT, MOVE_MUDDY_WATER,
		/*031F Èõ¶¡Óã*/

		POKE_MAREANIE + 20000, MOVE_HAZE, MOVE_SPIT_UP, MOVE_SWALLOW, MOVE_STOCKPILE,
		/*0320 ºÃ»µÐÇ*/

		POKE_MUDBRAY + 20000, MOVE_CLOSE_COMBAT, MOVE_MUD_BOMB, MOVE_DOUBLEEDGE, MOVE_BODY_SLAM, MOVE_MAGNITUDE,
		/*0322 ÄàÂ¿×Ð*/

		POKE_DEWPIDER + 20000, MOVE_AURORA_BEAM, MOVE_POWER_SPLIT, MOVE_STICKY_WEB, MOVE_SPIT_UP, MOVE_STOCKPILE,
		/*0324 µÎÖë*/

		POKE_FOMANTIS + 20000, MOVE_AROMATHERAPY, MOVE_LEAF_STORM, MOVE_WEATHER_BALL, MOVE_DEFOG, MOVE_GIGA_DRAIN,
		/*0326 Î±ó«²Ý*/

		POKE_MORELULL + 20000, MOVE_POISON_POWDER, MOVE_LEECH_SEED, MOVE_STUN_SPORE, MOVE_GROWTH, MOVE_AMNESIA,
		/*0328 Ë¯Ë¯¹½*/

		POKE_SALANDIT + 20000, MOVE_BELCH, MOVE_FAKE_OUT, MOVE_KNOCK_OFF, MOVE_SAND_ATTACK, MOVE_SNATCH,
		/*032A Ò¹µÁ»ðòá*/

		POKE_STUFFUL + 20000, MOVE_MEGA_KICK, MOVE_ICE_PUNCH, MOVE_STOMPING_TANTRUM, MOVE_FORCE_PALM, MOVE_WIDE_GUARD, MOVE_THUNDER_PUNCH, MOVE_ENDURE,
		/*032C Í¯Å¼ÐÜ*/

		POKE_BOUNSWEET + 20000, MOVE_GRASS_WHISTLE, MOVE_ACUPRESSURE, MOVE_SYNTHESIS, MOVE_CHARM, MOVE_PLAY_ROUGH, MOVE_FEINT,
		/*032E ÌðÖñÖñ*/

		POKE_COMFEY + 20000, MOVE_AFTER_YOU, MOVE_AMNESIA, MOVE_ENDURE, MOVE_LUCKY_CHANT,
		/*0331 »¨ÁÆ»·»·*/

		POKE_ORANGURU + 20000, MOVE_PSYCHIC_TERRAIN, MOVE_WONDER_ROOM, MOVE_EXTRASENSORY,
		/*0332 ÖÇ»ÓÐÉ*/

		POKE_PASSIMIAN + 20000, MOVE_SEISMIC_TOSS, MOVE_QUICK_ATTACK, MOVE_VITAL_THROW, MOVE_QUICK_GUARD, MOVE_IRON_HEAD, MOVE_FEINT,
		/*0333 Í¶ÖÀºï*/

		POKE_WIMPOD + 20000, MOVE_HARDEN, MOVE_WIDE_GUARD, MOVE_METAL_CLAW, MOVE_SPIKES, MOVE_AQUA_JET,
		/*0334 µ¨Ð¡³æ*/

		POKE_SANDYGAST + 20000, MOVE_SPIT_UP, MOVE_AMNESIA, MOVE_DESTINY_BOND, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_ANCIENT_POWER, MOVE_CURSE,
		/*0336 É³ÇðÍÞ*/

		POKE_PYUKUMUKU + 20000, MOVE_BESTOW, MOVE_VENOM_DRENCH, MOVE_TICKLE, MOVE_ENDURE, MOVE_SPITE,
		/*0338 È­º£²Î*/

		POKE_KOMALA + 20000, MOVE_SING, MOVE_WISH, MOVE_CHARM, MOVE_PLAY_ROUGH,
		/*033C Ê÷ÕíÎ²ÐÜ*/

		POKE_TURTONATOR + 20000, MOVE_REVENGE, MOVE_WIDE_GUARD, MOVE_FIRE_SPIN, MOVE_HEAD_SMASH,
		/*033D ±¬Ñæ¹êÊÞ*/

		POKE_TOGEDAMARU + 20000, MOVE_FAKE_OUT, MOVE_PRESENT, MOVE_DISARMING_VOICE, MOVE_TICKLE, MOVE_WISH, MOVE_REVERSAL, MOVE_TWINEEDLE, MOVE_ENCORE, MOVE_FLAIL,
		/*033E ÍÐ¸êµÂÂê¶û*/

		POKE_MIMIKYU + 20000, MOVE_NIGHTMARE, MOVE_DESTINY_BOND, MOVE_GRUDGE, MOVE_CURSE,
		/*033F ÃÕÄâQ*/

		POKE_BRUXISH + 20000, MOVE_ICE_FANG, MOVE_RAGE, MOVE_POISON_FANG, MOVE_WATER_PULSE,
		/*0340 Ä¥ÑÀ²ÊÆ¤Óã*/

		POKE_DRAMPA + 20000, MOVE_MIST, MOVE_HURRICANE, MOVE_DRAGON_RUSH, MOVE_PLAY_ROUGH, MOVE_RAZOR_WIND,
		/*0341 ÀÏÎÌÁú*/

		POKE_JANGMOO + 20000, MOVE_DRAGON_BREATH, MOVE_REVERSAL, MOVE_COUNTER,
		/*0343 ÐÄÁÛ±¦*/

		POKE_ALOLA_RATTATA + 20000, MOVE_REVENGE, MOVE_FINAL_GAMBIT, MOVE_UPROAR, MOVE_SWITCHEROO, MOVE_FURY_SWIPES, MOVE_REVERSAL, MOVE_SNATCH, MOVE_ME_FIRST, MOVE_COUNTER, MOVE_SWALLOW, MOVE_STOCKPILE,
		/*0358 Ð¡À­´ï°¢ÂÞÀ­*/

		POKE_ALOLA_SANDSHREW + 20000, MOVE_NIGHT_SLASH, MOVE_ICICLE_CRASH, MOVE_ICICLE_SPEAR, MOVE_METAL_CLAW, MOVE_HONE_CLAWS, MOVE_COUNTER, MOVE_AMNESIA, MOVE_CRUSH_CLAW, MOVE_ENDURE, MOVE_CHIP_AWAY, MOVE_FLAIL, MOVE_CURSE,
		/*035B ´©É½Êó°¢ÂÞÀ­*/

		POKE_ALOLA_VULPIX + 20000, MOVE_HYPNOSIS, MOVE_DISABLE, MOVE_AGILITY, MOVE_FREEZEDRY, MOVE_POWER_SWAP, MOVE_SECRET_POWER, MOVE_CHARM, MOVE_TAIL_SLAP, MOVE_EXTRASENSORY, MOVE_SPITE, MOVE_MOONBLAST, MOVE_ENCORE, MOVE_HOWL, MOVE_FLAIL,
		/*035D ÁùÎ²°¢ÂÞÀ­*/

		POKE_ALOLA_DIGLETT + 20000, MOVE_FINAL_GAMBIT, MOVE_FEINT_ATTACK, MOVE_THRASH, MOVE_METAL_SOUND, MOVE_MEMENTO, MOVE_REVERSAL, MOVE_ENDURE, MOVE_HEADBUTT, MOVE_BEAT_UP, MOVE_ANCIENT_POWER, MOVE_PURSUIT,
		/*035F µØÊó°¢ÂÞÀ­*/

		POKE_ALOLA_MEOWTH + 20000, MOVE_PUNISHMENT, MOVE_FLATTER, MOVE_HYPNOSIS, MOVE_ASSIST, MOVE_COVET, MOVE_PARTING_SHOT, MOVE_FOUL_PLAY, MOVE_SNATCH, MOVE_CHARM, MOVE_AMNESIA, MOVE_SPITE, MOVE_FLAIL,
		/*0361 ß÷ß÷°¢ÂÞÀ­*/

		POKE_ALOLA_GEODUDE + 20000, MOVE_SCREECH, MOVE_BLOCK, MOVE_MAGNET_RISE, MOVE_WIDE_GUARD, MOVE_ROCK_CLIMB, MOVE_AUTOTOMIZE, MOVE_COUNTER, MOVE_ENDURE, MOVE_FLAIL, MOVE_CURSE,
		/*0363 Ð¡È­Ê¯°¢ÂÞÀ­*/

		POKE_ALOLA_GRIMER + 20000, MOVE_ASSURANCE, MOVE_IMPRISON, MOVE_SCARY_FACE, MOVE_MEAN_LOOK, MOVE_SPIT_UP, MOVE_CLEAR_SMOG, MOVE_SWALLOW, MOVE_STOCKPILE, MOVE_SHADOW_SNEAK, MOVE_SPITE, MOVE_OBLIVION_WING, MOVE_PURSUIT, MOVE_CURSE,
		/*0366 ³ôÄà°¢ÂÞÀ­*/

		POKE_BASCULIN_BLUE + 20000, MOVE_REVENGE, MOVE_WHIRLPOOL, MOVE_RAGE, MOVE_SWIFT, MOVE_AGILITY, MOVE_MUD_SHOT, MOVE_BUBBLE_BEAM, MOVE_HEAD_SMASH, MOVE_BRINE, MOVE_MUDDY_WATER,
		/*03C6 Ò°ÂùöÔÓãÀ¶*/

		POKE_ORICORIO_PACHI + 20000, MOVE_SAFEGUARD, MOVE_TAILWIND, MOVE_CAPTIVATE, MOVE_PLUCK,
		/*03CC »¨ÎèÄñµç*/

		POKE_ORICORIO_FURA + 20000, MOVE_SAFEGUARD, MOVE_TAILWIND, MOVE_CAPTIVATE, MOVE_PLUCK,
		/*03CD »¨ÎèÄñ³¬*/

		POKE_ORICORIO_MAI + 20000, MOVE_SAFEGUARD, MOVE_TAILWIND, MOVE_CAPTIVATE, MOVE_PLUCK,
		/*03CE »¨ÎèÄñÓÄ*/

		POKE_SHELLOS_PINK + 20000, MOVE_MIST, MOVE_FISSURE, MOVE_YAWN, MOVE_MIRROR_COAT, MOVE_MEMENTO, MOVE_SPIT_UP, MOVE_CLEAR_SMOG, MOVE_ACID_ARMOR, MOVE_COUNTER, MOVE_AMNESIA, MOVE_SWALLOW, MOVE_TRUMP_CARD, MOVE_SLUDGE, MOVE_STOCKPILE, MOVE_BRINE, MOVE_CURSE,
		/*03D8 ÎÞ¿Çº£ÍÃ·Û*/

		POKE_FRILLISH_FEMALE + 20000, MOVE_MIST, MOVE_CONSTRICT, MOVE_PAIN_SPLIT, MOVE_CONFUSE_RAY, MOVE_ACID_ARMOR, MOVE_RECOVER,
		/*03DB ÇáÆ®Æ®·Û*/

		POKE_FLABEBE_ORANGE + 20000, MOVE_CAMOUFLAGE, MOVE_COPYCAT, MOVE_TEARFUL_LOOK, MOVE_CAPTIVATE,
		/*0404 »¨ÝíÝí³È*/

		POKE_FLABEBE_BLUE + 20000, MOVE_CAMOUFLAGE, MOVE_COPYCAT, MOVE_TEARFUL_LOOK, MOVE_CAPTIVATE,
		/*0405 »¨ÝíÝíÀ¶*/

		POKE_FLABEBE_WHITE + 20000, MOVE_CAMOUFLAGE, MOVE_COPYCAT, MOVE_TEARFUL_LOOK, MOVE_CAPTIVATE,
		/*0406 »¨ÝíÝí°×*/

		POKE_FLABEBE_YELLOW + 20000, MOVE_CAMOUFLAGE, MOVE_COPYCAT, MOVE_TEARFUL_LOOK, MOVE_CAPTIVATE,
		/*0407 »¨ÝíÝí»Æ*/

		POKE_DEERLING_SUMMER + 20000, MOVE_GRASS_WHISTLE, MOVE_WORRY_SEED, MOVE_AGILITY, MOVE_SYNTHESIS, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_SLEEP_TALK, MOVE_ODOR_SLEUTH, MOVE_HEADBUTT, MOVE_NATURAL_GIFT,
		/*0423 ËÄ¼¾Â¹ÏÄ*/

		POKE_DEERLING_AUTUMN + 20000, MOVE_GRASS_WHISTLE, MOVE_WORRY_SEED, MOVE_AGILITY, MOVE_SYNTHESIS, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_SLEEP_TALK, MOVE_ODOR_SLEUTH, MOVE_HEADBUTT, MOVE_NATURAL_GIFT,
		/*0424 ËÄ¼¾Â¹Çï*/

		POKE_DEERLING_WINTER + 20000, MOVE_GRASS_WHISTLE, MOVE_WORRY_SEED, MOVE_AGILITY, MOVE_SYNTHESIS, MOVE_FAKE_TEARS, MOVE_BATON_PASS, MOVE_SLEEP_TALK, MOVE_ODOR_SLEUTH, MOVE_HEADBUTT, MOVE_NATURAL_GIFT,
		/*0425 ËÄ¼¾Â¹¶¬*/

		0xFFFF};
